import Foundation
@testable import Domain

// Wires SplitsCollapse.swift into FunctionRegistry.
//
// `collapseSplitRowIds`'s vectors were generated by importing web's REAL
// `collapseSplitRows` and running it. `splitInfoByTransaction`'s were
// transcribed from `useSplitInfo`, which is a React hook and cannot be called
// from node — the transcription was diffed against collapse.ts line by line.

private func optionalString(_ any: Any?) -> String? {
    guard let any, !(any is NSNull) else { return nil }
    return any as? String
}

private func postings(_ arr: [Any]) -> [SplitPosting] {
    arr.map { entry in
        let o = entry as! [String: Any]
        return SplitPosting(
            transactionId: o["transactionId"] as! String,
            expenseId: o["expenseId"] as! String,
            role: o["role"] as! String,
            amountMinor: (o["amountMinor"] as! NSNumber).int64Value,
            currency: o["currency"] as! String,
            groupId: optionalString(o["groupId"])
        )
    }
}

private func infoToJson(_ i: SplitInfo) -> [String: Any] {
    [
        "expenseId": i.expenseId,
        // `.map { $0 as Any } ?? NSNull()`, NOT `as Any? ?? NSNull()`: casting a
        // nil Optional to `Any?` produces a NON-nil `Any?` wrapping the nil, so
        // `??` never fires and the dictionary ends up holding a wrapped nil
        // that compares equal to nothing.
        "groupId": i.groupId.map { $0 as Any } ?? NSNull(),
        "displayPaid": i.displayPaid,
        "yourShare": i.yourShare,
        "owedToYou": i.owedToYou,
        "youOwe": i.youOwe,
        "currency": i.currency,
    ]
}

private func infoFromJson(_ o: [String: Any]) -> SplitInfo {
    SplitInfo(
        expenseId: o["expenseId"] as! String,
        groupId: optionalString(o["groupId"]),
        displayPaid: (o["displayPaid"] as! NSNumber).int64Value,
        yourShare: (o["yourShare"] as! NSNumber).int64Value,
        owedToYou: (o["owedToYou"] as! NSNumber).int64Value,
        youOwe: (o["youOwe"] as! NSNumber).int64Value,
        currency: o["currency"] as! String
    )
}

func registerSplitsCollapseVectors() {
    FunctionRegistry.register(domain: "splits-collapse", fn: "splitInfoByTransaction") { input in
        let d = input as! [String: Any]
        let map = splitInfoByTransaction(postings(d["rows"] as! [Any]))
        return map.mapValues(infoToJson)
    }

    FunctionRegistry.register(domain: "splits-collapse", fn: "collapseSplitRowIds") { input in
        let d = input as! [String: Any]
        let ids = (d["ids"] as! [Any]).map { $0 as! String }
        let info = (d["info"] as! [String: Any]).mapValues { infoFromJson($0 as! [String: Any]) }
        return collapseSplitRowIds(ids, info)
    }
}
