import Foundation
@testable import Domain

// Wires Suggestions.swift into FunctionRegistry.
//
// The corpus is GENERATED by running web's own `@sanvya/suggestions` over the
// case list, so what is pinned here is ground truth rather than a transcription
// of it. That matters more than usual for this domain: every rule is a
// threshold, and a transcription that read `>= 15` as `> 15` would be invisible
// until someone with exactly fifteen transactions never saw a budget card.

private func count(_ d: [String: Any], _ key: String) -> Int {
    (d[key] as? NSNumber)?.intValue ?? 0
}

private func usageCounts(_ d: [String: Any]) -> UsageCounts {
    UsageCounts(
        accounts: count(d, "accounts"),
        transactions: count(d, "transactions"),
        subscriptions: count(d, "subscriptions"),
        loans: count(d, "loans"),
        budgets: count(d, "budgets"),
        goals: count(d, "goals"),
        splitGroups: count(d, "splitGroups"),
        receipts: count(d, "receipts"),
        recurring: count(d, "recurring"),
        holdings: count(d, "holdings"),
        creditCards: count(d, "creditCards"),
        creditCardAccounts: count(d, "creditCardAccounts")
    )
}

func registerSuggestionsVectors() {
    FunctionRegistry.register(domain: "suggestions", fn: "pickSuggestions") { input in
        let d = input as! [String: Any]
        let picked = pickSuggestions(
            usage: usageCounts(d["usage"] as! [String: Any]),
            dismissed: Set((d["dismissed"] as! [Any]).map { $0 as! String }),
            isPaid: (d["isPaid"] as! NSNumber).boolValue,
            max: (d["max"] as! NSNumber).intValue
        )
        // The raw values, not the case names: what crosses the wire (and what a
        // dismissal persists) is web's own string union.
        return picked.map { $0.rawValue } as [Any]
    }
}
