package com.sanvya.app.theme

// GENERATED FILE — do not hand-edit.
// Source: apps/web/src/ui/MaterialIcon.tsx (MATERIAL_ICON)
// Regenerate with: node tools/parity/generate-icons.mjs
// Adding an icon also requires rebuilding the font: tools/parity/build-fonts.sh

/**
 * Material Symbols Rounded codepoints, drawn from the bundled subset font
 * (`res/font/sanvya_icons.ttf`) — the same 4 KB subset web serves, so a glyph
 * is identical across web, Android and iOS.
 *
 * Rendered as text, not as an ImageVector: the subset is generated by
 * codepoint, and a codepoint that fails to resolve paints nothing, whereas a
 * ligature-based lookup would paint the literal word "space_dashboard" into
 * the navigation bar.
 */
object SanvyaIcons {
    const val accountBalance = "\ue84f"
    const val add = "\ue145"
    const val apartment = "\uea40"
    const val arrowBack = "\ue5c4"
    const val autoAwesome = "\ue65f"
    const val autorenew = "\ue028"
    const val bolt = "\uea0b"
    const val bookmarks = "\ue98b"
    const val callSplit = "\ue0b6"
    const val category = "\ue574"
    const val chatBubble = "\ue0ca"
    const val check = "\ue5ca"
    const val chevronRight = "\ue409"
    const val close = "\ue14c"
    const val creditCard = "\ue870"
    const val currencyBitcoin = "\uebc5"
    const val delete = "\ue872"
    const val description = "\ue683"
    const val directionsCar = "\ue531"
    const val donutSmall = "\ue918"
    const val edit = "\ue150"
    const val expandMore = "\ue5cf"
    const val fitnessCenter = "\ueb43"
    const val flag = "\ue153"
    const val folder = "\ue2c7"
    const val groups = "\uf233"
    const val healthAndSafety = "\ue1d5"
    const val help = "\ue887"
    const val home = "\ue88a"
    const val insights = "\uf092"
    const val label = "\ue892"
    const val lock = "\ue897"
    const val moreHoriz = "\ue5d3"
    const val notifications = "\ue7f4"
    const val payments = "\uef63"
    const val person = "\ue7fd"
    const val pieChart = "\ue6c4"
    const val receipt = "\ue8b0"
    const val receiptLong = "\uef6e"
    const val redeem = "\ue8b1"
    const val requestQuote = "\uf1b6"
    const val restaurant = "\ue56c"
    const val savings = "\ue2eb"
    const val school = "\ue80c"
    const val search = "\ue8b6"
    const val sell = "\ue54e"
    const val settings = "\ue8b8"
    const val showChart = "\ue6e1"
    const val spaceDashboard = "\ue66b"
    const val subscriptions = "\ue064"
    const val swapHoriz = "\ue8d4"
    const val syncProblem = "\ue629"
    const val trendingUp = "\ue8e5"
    const val volunteerActivism = "\uea70"
    const val wallet = "\uf8ff"
    const val waterfallChart = "\uea00"
    const val wifi = "\ue63e"
    const val work = "\ue8f9"

    /** Web's own name for the icon, for spec cross-checks and tests. */
    val byWebName: Map<String, String> = mapOf(
        "account_balance" to "\ue84f",
        "add" to "\ue145",
        "apartment" to "\uea40",
        "arrow_back" to "\ue5c4",
        "auto_awesome" to "\ue65f",
        "autorenew" to "\ue028",
        "bolt" to "\uea0b",
        "bookmarks" to "\ue98b",
        "call_split" to "\ue0b6",
        "category" to "\ue574",
        "chat_bubble" to "\ue0ca",
        "check" to "\ue5ca",
        "chevron_right" to "\ue409",
        "close" to "\ue14c",
        "credit_card" to "\ue870",
        "currency_bitcoin" to "\uebc5",
        "delete" to "\ue872",
        "description" to "\ue683",
        "directions_car" to "\ue531",
        "donut_small" to "\ue918",
        "edit" to "\ue150",
        "expand_more" to "\ue5cf",
        "fitness_center" to "\ueb43",
        "flag" to "\ue153",
        "folder" to "\ue2c7",
        "groups" to "\uf233",
        "health_and_safety" to "\ue1d5",
        "help" to "\ue887",
        "home" to "\ue88a",
        "insights" to "\uf092",
        "label" to "\ue892",
        "lock" to "\ue897",
        "more_horiz" to "\ue5d3",
        "notifications" to "\ue7f4",
        "payments" to "\uef63",
        "person" to "\ue7fd",
        "pie_chart" to "\ue6c4",
        "receipt" to "\ue8b0",
        "receipt_long" to "\uef6e",
        "redeem" to "\ue8b1",
        "request_quote" to "\uf1b6",
        "restaurant" to "\ue56c",
        "savings" to "\ue2eb",
        "school" to "\ue80c",
        "search" to "\ue8b6",
        "sell" to "\ue54e",
        "settings" to "\ue8b8",
        "show_chart" to "\ue6e1",
        "space_dashboard" to "\ue66b",
        "subscriptions" to "\ue064",
        "swap_horiz" to "\ue8d4",
        "sync_problem" to "\ue629",
        "trending_up" to "\ue8e5",
        "volunteer_activism" to "\uea70",
        "wallet" to "\uf8ff",
        "waterfall_chart" to "\uea00",
        "wifi" to "\ue63e",
        "work" to "\ue8f9",
    )
}
