package com.sanvya.app.domain.splits

import com.sanvya.app.domain.vectors.FunctionRegistry
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.long
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive

// Wires Collapse.kt into FunctionRegistry.
//
// `collapseSplitRowIds`'s vectors were generated by importing web's REAL
// `collapseSplitRows` and running it. `splitInfoByTransaction`'s were
// transcribed from `useSplitInfo`, which is a React hook and cannot be called
// from node -- the transcription was diffed against collapse.ts line by line.

private const val DOMAIN = "splits-collapse"

private fun nullableString(v: JsonElement?): String? =
    if (v == null || v is JsonNull) null else v.jsonPrimitive.content

private fun postings(arr: JsonArray): List<SplitPosting> = arr.map { entry ->
    val o = entry.jsonObject
    SplitPosting(
        transactionId = o.getValue("transactionId").jsonPrimitive.content,
        expenseId = o.getValue("expenseId").jsonPrimitive.content,
        role = o.getValue("role").jsonPrimitive.content,
        amountMinor = o.getValue("amountMinor").jsonPrimitive.long,
        currency = o.getValue("currency").jsonPrimitive.content,
        groupId = nullableString(o["groupId"]),
    )
}

private fun infoToJson(i: SplitInfo): JsonObject = JsonObject(
    mapOf(
        "expenseId" to JsonPrimitive(i.expenseId),
        "groupId" to (i.groupId?.let { JsonPrimitive(it) } ?: JsonNull),
        "displayPaid" to JsonPrimitive(i.displayPaid),
        "yourShare" to JsonPrimitive(i.yourShare),
        "owedToYou" to JsonPrimitive(i.owedToYou),
        "youOwe" to JsonPrimitive(i.youOwe),
        "currency" to JsonPrimitive(i.currency),
    )
)

private fun infoFromJson(o: JsonObject): SplitInfo = SplitInfo(
    expenseId = o.getValue("expenseId").jsonPrimitive.content,
    groupId = nullableString(o["groupId"]),
    displayPaid = o.getValue("displayPaid").jsonPrimitive.long,
    yourShare = o.getValue("yourShare").jsonPrimitive.long,
    owedToYou = o.getValue("owedToYou").jsonPrimitive.long,
    youOwe = o.getValue("youOwe").jsonPrimitive.long,
    currency = o.getValue("currency").jsonPrimitive.content,
)

fun registerSplitsCollapseVectors() {
    FunctionRegistry.register(DOMAIN, "splitInfoByTransaction") { input ->
        val rows = postings(input.jsonObject.getValue("rows").jsonArray)
        JsonObject(splitInfoByTransaction(rows).mapValues { (_, info) -> infoToJson(info) })
    }

    FunctionRegistry.register(DOMAIN, "collapseSplitRowIds") { input ->
        val o = input.jsonObject
        val ids = o.getValue("ids").jsonArray.map { it.jsonPrimitive.content }
        val info = o.getValue("info").jsonObject.mapValues { (_, v) -> infoFromJson(v.jsonObject) }
        JsonArray(collapseSplitRowIds(ids, info).map { JsonPrimitive(it) })
    }
}
