import Foundation

// GENERATED by tools/parity/generate-tiles.mjs -- do not edit by hand.
// Sources: apps/web/src/dashboard.ts and apps/web/src/dashboard/tiles.tsx.
// Run `node tools/parity/generate-tiles.mjs` after changing either.

/// How wide a tile sits in the dashboard grid.
///
/// Three steps, not a free drag. Web offers exactly these and stores the chosen
/// step rather than a pixel width, which is what lets the same saved dashboard
/// open on a phone and an iPad without arriving half off-screen.
enum TileWidth: String, CaseIterable, Sendable {
    case sm
    case md
    case lg

    var columns: Int {
        switch self {
        case .sm: return 1
        case .md: return 2
        case .lg: return 4
        }
    }

    /// Cycles on tap, exactly as web's width button does.
    var next: TileWidth {
        let all = TileWidth.allCases
        return all[(all.firstIndex(of: self)! + 1) % all.count]
    }
}

/// Every dashboard tile, in catalog order.
enum TileId: String, CaseIterable, Identifiable, Sendable {
    case recent
    case spending
    case upcoming
    case trends
    case splits
    case budgets
    case goals
    case subscriptions
    case cashflow
    case netTrend
    case byCategory
    case byLabel
    case monthCompare
    case currencies

    var id: String { rawValue }

    var isPremium: Bool {
        switch self {
        case .cashflow, .netTrend, .byCategory, .byLabel, .monthCompare: return true
        default: return false
        }
    }

    /// Where a tap on the tile goes, mirroring web's TILE_HREF.
    var destination: NavTab {
        switch self {
        case .recent: return .transactions
        case .spending: return .transactions
        case .upcoming: return .recurring
        case .trends: return .insights
        case .splits: return .splits
        case .budgets: return .budgets
        case .goals: return .goals
        case .subscriptions: return .recurring
        case .cashflow: return .insights
        case .netTrend: return .insights
        case .byCategory: return .insights
        case .byLabel: return .insights
        case .monthCompare: return .insights
        case .currencies: return .accounts
        }
    }

    var title: String {
        switch self {
        case .recent: return S.Dashboard.tileRecent
        case .spending: return S.Dashboard.tileSpending
        case .upcoming: return S.Dashboard.tileUpcoming
        case .trends: return S.Dashboard.tileTrends
        case .splits: return S.Dashboard.tileSplits
        case .budgets: return S.Dashboard.tileBudgets
        case .goals: return S.Dashboard.tileGoals
        case .subscriptions: return S.Dashboard.tileSubscriptions
        case .cashflow: return S.Dashboard.tileCashflow
        case .netTrend: return S.Dashboard.tileNetTrend
        case .byCategory: return S.Dashboard.tileByCategory
        case .byLabel: return S.Dashboard.tileByLabel
        case .monthCompare: return S.Dashboard.tileMonthCompare
        case .currencies: return S.Dashboard.tileCurrencies
        }
    }
}

/// What a fresh install shows before the user touches anything.
let defaultTileIds: [TileId] = [.recent, .spending, .upcoming]

/// Storage keys, shared verbatim with web so a preference means one thing.
let tileOrderKey = "dashboardTiles"
let tileSizeKey = "dashboardTileSizes"
