package com.sanvya.app.data.security

import android.content.Context
import android.content.SharedPreferences
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import com.sanvya.app.domain.security.SECURITY_GCM_TAG_LENGTH_BITS
import com.sanvya.app.domain.security.SECURITY_IV_LENGTH_BYTES
import java.security.KeyStore
import java.util.Base64
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Where an unlocked DEK lives between launches.
 *
 * WHY THIS EXISTS AT ALL, GIVEN WEB HAS NO EQUIVALENT. In a browser the DEK is
 * a module-level variable and a page reload re-locks the session — that is
 * `apps/web/src/crypto/session.ts`'s whole storage story. A phone cannot copy
 * that: Android kills a backgrounded process whenever it likes, invisibly, so
 * a memory-only DEK would silently re-lock the app several times a day and
 * demand a 20-character passphrase each time. Nobody would keep encryption on.
 *
 * So the unlock persists, and it persists in the one place on Android that is
 * meant for this. NOT `SharedPreferences` in the clear, and not
 * `EncryptedSharedPreferences` either — `androidx.security-crypto` is a
 * deprecated library and adding a dependency to get what the platform already
 * provides is the wrong trade. This is what that library does underneath: a
 * hardware-backed AES-GCM key that never leaves the Keystore, wrapping the
 * secret, with only the wrapped form in a private prefs file.
 *
 * WHAT THIS DOES AND DOES NOT PROTECT. It protects against the threat the
 * encryption feature is about: the server, and anyone with the database. It
 * does not protect against somebody holding your unlocked phone — but neither
 * does anything else here, because the ledger's amounts, accounts and dates
 * are plaintext in the local SQLite by design (see SECURITY_ENCRYPTION_PLAN.md
 * — that is the "Hybrid" in Hybrid zero-trust). Explicit Lock and sign-out
 * both erase these entries.
 */
class SecureKeyStore(context: Context) {

    private val prefs: SharedPreferences =
        context.applicationContext.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)

    /** Store [value] under [name], wrapped by the Keystore key. */
    fun put(name: String, value: ByteArray) {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, wrappingKey())
        val sealed = cipher.doFinal(value)
        // iv ‖ ciphertext ‖ tag. The IV is generated by the Keystore provider
        // (it refuses a caller-supplied one for GCM, to make reuse impossible)
        // so it has to be read back off the cipher and stored alongside.
        val packed = cipher.iv + sealed
        prefs.edit().putString(name, Base64.getEncoder().encodeToString(packed)).apply()
    }

    /** Read [name] back, or null if absent or no longer decryptable. */
    fun get(name: String): ByteArray? {
        val stored = prefs.getString(name, null) ?: return null
        return try {
            val packed = Base64.getDecoder().decode(stored)
            if (packed.size <= SECURITY_IV_LENGTH_BYTES) return null
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(
                Cipher.DECRYPT_MODE,
                wrappingKey(),
                GCMParameterSpec(SECURITY_GCM_TAG_LENGTH_BITS, packed, 0, SECURITY_IV_LENGTH_BYTES),
            )
            cipher.doFinal(packed, SECURITY_IV_LENGTH_BYTES, packed.size - SECURITY_IV_LENGTH_BYTES)
        } catch (_: Exception) {
            // The Keystore key is gone (device reset, app data cleared, an OS
            // upgrade that invalidated it). There is nothing to recover and
            // nothing to report: the user simply has to unlock again, which is
            // exactly what a null return produces.
            remove(name)
            null
        }
    }

    /** Erase one entry. Used by Lock and by sign-out. */
    fun remove(name: String) {
        prefs.edit().remove(name).apply()
    }

    /**
     * The Keystore-resident AES key that wraps everything above.
     *
     * Created on first use and never exported — `getKey` hands back a handle,
     * not bytes. `setUserAuthenticationRequired` is deliberately NOT set: it
     * would make every read require a biometric prompt, which is a different
     * product decision from the one web made and not one to smuggle in here.
     */
    private fun wrappingKey(): SecretKey {
        val keyStore = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }
        (keyStore.getKey(KEY_ALIAS, null) as? SecretKey)?.let { return it }
        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE)
        generator.init(
            KeyGenParameterSpec.Builder(
                KEY_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .build(),
        )
        return generator.generateKey()
    }

    private companion object {
        const val PREFS_NAME = "sanvya_secure_keys"
        const val ANDROID_KEYSTORE = "AndroidKeyStore"
        const val KEY_ALIAS = "sanvya.security.wrapping"
        const val TRANSFORMATION = "AES/GCM/NoPadding"
    }
}
