package com.sanvya.app.domain.db

/**
 * Mirrors packages/db/src/index.ts's `AppSchema` (the PowerSync client
 * schema / local SQLite mirror), generated from
 * tools/golden-vectors/vectors/mobile-schema.json by
 * tools/golden-vectors/gen-mobile-schema.mjs. DO NOT HAND-EDIT — see that
 * script's header for how to regenerate after packages/db/src/index.ts
 * changes, and how this doubles as the schema-parity check across all three
 * platforms.
 * 
 * Every table has an implicit `id: TEXT` primary key managed by PowerSync
 * itself; it is intentionally omitted from `columns` below (present on every
 * table, so listing it 63 times would be noise, not information) and is
 * assumed by any code consuming this schema.
 * 
 * This is a data-driven schema DESCRIPTOR (table/column names, SQLite
 * storage type, indexes, local-only flags) — not per-table row model
 * classes. Strongly-typed row models are P2.5 (repositories) territory,
 * once the local SQLite driver is chosen for each platform.
 */

enum class ColumnType { TEXT, INTEGER, REAL }

data class ColumnDef(val name: String, val type: ColumnType)

data class IndexColumnDef(val name: String, val ascending: Boolean, val type: ColumnType)

data class IndexDef(val name: String, val columns: List<IndexColumnDef>)

data class TableDef(
    val name: String,
    val viewName: String,
    val columns: List<ColumnDef>,
    val indexes: List<IndexDef>,
    val localOnly: Boolean,
    val insertOnly: Boolean,
)

object PocketCareSchema {
    val tables: List<TableDef> = listOf(
        TableDef(
            name = "account_type_payment_methods",
            viewName = "account_type_payment_methods",
            columns = listOf(
                ColumnDef("account_type_id", ColumnType.TEXT),
                ColumnDef("payment_method_id", ColumnType.TEXT),
            ),
            indexes = emptyList(),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "account_types",
            viewName = "account_types",
            columns = listOf(
                ColumnDef("label", ColumnType.TEXT),
                ColumnDef("sort", ColumnType.INTEGER),
            ),
            indexes = emptyList(),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "accounts",
            viewName = "accounts",
            columns = listOf(
                ColumnDef("user_id", ColumnType.TEXT),
                ColumnDef("name", ColumnType.TEXT),
                ColumnDef("type", ColumnType.TEXT),
                ColumnDef("currency", ColumnType.TEXT),
                ColumnDef("icon", ColumnType.TEXT),
                ColumnDef("color", ColumnType.TEXT),
                ColumnDef("is_archived", ColumnType.INTEGER),
                ColumnDef("include_in_net_worth", ColumnType.INTEGER),
                ColumnDef("allow_negative", ColumnType.INTEGER),
                ColumnDef("kind", ColumnType.TEXT),
                ColumnDef("created_at", ColumnType.TEXT),
                ColumnDef("updated_at", ColumnType.TEXT),
                ColumnDef("deleted_at", ColumnType.TEXT),
            ),
            indexes = emptyList(),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "assistant_memory",
            viewName = "assistant_memory",
            columns = listOf(
                ColumnDef("user_id", ColumnType.TEXT),
                ColumnDef("notes", ColumnType.TEXT),
                ColumnDef("created_at", ColumnType.TEXT),
                ColumnDef("updated_at", ColumnType.TEXT),
            ),
            indexes = emptyList(),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "assistant_messages",
            viewName = "assistant_messages",
            columns = listOf(
                ColumnDef("user_id", ColumnType.TEXT),
                ColumnDef("thread_id", ColumnType.TEXT),
                ColumnDef("role", ColumnType.TEXT),
                ColumnDef("content", ColumnType.TEXT),
                ColumnDef("created_at", ColumnType.TEXT),
                ColumnDef("updated_at", ColumnType.TEXT),
            ),
            indexes = listOf(
                IndexDef("by_thread", listOf(IndexColumnDef("thread_id", true, ColumnType.TEXT), IndexColumnDef("created_at", true, ColumnType.TEXT))),
            ),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "assistant_threads",
            viewName = "assistant_threads",
            columns = listOf(
                ColumnDef("user_id", ColumnType.TEXT),
                ColumnDef("title", ColumnType.TEXT),
                ColumnDef("created_at", ColumnType.TEXT),
                ColumnDef("updated_at", ColumnType.TEXT),
                ColumnDef("deleted_at", ColumnType.TEXT),
            ),
            indexes = emptyList(),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "budget_categories",
            viewName = "budget_categories",
            columns = listOf(
                ColumnDef("user_id", ColumnType.TEXT),
                ColumnDef("budget_id", ColumnType.TEXT),
                ColumnDef("category_id", ColumnType.TEXT),
            ),
            indexes = emptyList(),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "budget_labels",
            viewName = "budget_labels",
            columns = listOf(
                ColumnDef("user_id", ColumnType.TEXT),
                ColumnDef("budget_id", ColumnType.TEXT),
                ColumnDef("label_id", ColumnType.TEXT),
            ),
            indexes = emptyList(),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "budgets",
            viewName = "budgets",
            columns = listOf(
                ColumnDef("user_id", ColumnType.TEXT),
                ColumnDef("name", ColumnType.TEXT),
                ColumnDef("period", ColumnType.TEXT),
                ColumnDef("start_date", ColumnType.TEXT),
                ColumnDef("end_date", ColumnType.TEXT),
                ColumnDef("limit_amount", ColumnType.INTEGER),
                ColumnDef("currency", ColumnType.TEXT),
                ColumnDef("threshold_pct", ColumnType.INTEGER),
                ColumnDef("alert_time_utc", ColumnType.TEXT),
                ColumnDef("rollover", ColumnType.INTEGER),
                ColumnDef("created_at", ColumnType.TEXT),
                ColumnDef("updated_at", ColumnType.TEXT),
                ColumnDef("deleted_at", ColumnType.TEXT),
            ),
            indexes = emptyList(),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "bug_reports",
            viewName = "bug_reports",
            columns = listOf(
                ColumnDef("user_id", ColumnType.TEXT),
                ColumnDef("diagnostics", ColumnType.TEXT),
                ColumnDef("kind", ColumnType.TEXT),
                ColumnDef("severity", ColumnType.TEXT),
                ColumnDef("area", ColumnType.TEXT),
                ColumnDef("title", ColumnType.TEXT),
                ColumnDef("description", ColumnType.TEXT),
                ColumnDef("app_version", ColumnType.TEXT),
                ColumnDef("route", ColumnType.TEXT),
                ColumnDef("platform", ColumnType.TEXT),
                ColumnDef("user_agent", ColumnType.TEXT),
                ColumnDef("viewport", ColumnType.TEXT),
                ColumnDef("online", ColumnType.INTEGER),
                ColumnDef("status", ColumnType.TEXT),
                ColumnDef("created_at", ColumnType.TEXT),
                ColumnDef("updated_at", ColumnType.TEXT),
            ),
            indexes = emptyList(),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "categories",
            viewName = "categories",
            columns = listOf(
                ColumnDef("user_id", ColumnType.TEXT),
                ColumnDef("name", ColumnType.TEXT),
                ColumnDef("kind", ColumnType.TEXT),
                ColumnDef("icon", ColumnType.TEXT),
                ColumnDef("color", ColumnType.TEXT),
                ColumnDef("is_system", ColumnType.INTEGER),
                ColumnDef("parent_id", ColumnType.TEXT),
                ColumnDef("created_at", ColumnType.TEXT),
                ColumnDef("updated_at", ColumnType.TEXT),
                ColumnDef("deleted_at", ColumnType.TEXT),
            ),
            indexes = emptyList(),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "category_kinds",
            viewName = "category_kinds",
            columns = listOf(
                ColumnDef("label", ColumnType.TEXT),
                ColumnDef("sort", ColumnType.INTEGER),
            ),
            indexes = emptyList(),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "category_rules",
            viewName = "category_rules",
            columns = listOf(
                ColumnDef("user_id", ColumnType.TEXT),
                ColumnDef("kind", ColumnType.TEXT),
                ColumnDef("key", ColumnType.TEXT),
                ColumnDef("category_id", ColumnType.TEXT),
                ColumnDef("weight", ColumnType.INTEGER),
                ColumnDef("corrections", ColumnType.INTEGER),
                ColumnDef("created_at", ColumnType.TEXT),
                ColumnDef("updated_at", ColumnType.TEXT),
                ColumnDef("deleted_at", ColumnType.TEXT),
            ),
            indexes = listOf(
                IndexDef("by_user_key", listOf(IndexColumnDef("user_id", true, ColumnType.TEXT), IndexColumnDef("key", true, ColumnType.TEXT))),
            ),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "commitment_kinds",
            viewName = "commitment_kinds",
            columns = listOf(
                ColumnDef("label", ColumnType.TEXT),
                ColumnDef("sort", ColumnType.INTEGER),
            ),
            indexes = emptyList(),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "connections",
            viewName = "connections",
            columns = listOf(
                ColumnDef("user_a", ColumnType.TEXT),
                ColumnDef("user_b", ColumnType.TEXT),
                ColumnDef("created_at", ColumnType.TEXT),
                ColumnDef("deleted_at", ColumnType.TEXT),
            ),
            indexes = emptyList(),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "coupons",
            viewName = "coupons",
            columns = listOf(
                ColumnDef("code", ColumnType.TEXT),
                ColumnDef("user_id", ColumnType.TEXT),
                ColumnDef("tier", ColumnType.TEXT),
                ColumnDef("months", ColumnType.INTEGER),
                ColumnDef("reason", ColumnType.TEXT),
                ColumnDef("expires_at", ColumnType.TEXT),
                ColumnDef("redeemed_at", ColumnType.TEXT),
                ColumnDef("applied_until", ColumnType.TEXT),
                ColumnDef("created_at", ColumnType.TEXT),
            ),
            indexes = emptyList(),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "credit_card_details",
            viewName = "credit_card_details",
            columns = listOf(
                ColumnDef("user_id", ColumnType.TEXT),
                ColumnDef("account_id", ColumnType.TEXT),
                ColumnDef("statement_day", ColumnType.INTEGER),
                ColumnDef("due_day", ColumnType.INTEGER),
                ColumnDef("credit_limit", ColumnType.INTEGER),
                ColumnDef("card_last4", ColumnType.TEXT),
                ColumnDef("pending_due", ColumnType.INTEGER),
                ColumnDef("due_on", ColumnType.TEXT),
                ColumnDef("created_at", ColumnType.TEXT),
                ColumnDef("updated_at", ColumnType.TEXT),
            ),
            indexes = emptyList(),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "entitlements",
            viewName = "entitlements",
            columns = listOf(
                ColumnDef("user_id", ColumnType.TEXT),
                ColumnDef("tier", ColumnType.TEXT),
                ColumnDef("source", ColumnType.TEXT),
                ColumnDef("expires_at", ColumnType.TEXT),
                ColumnDef("monthly_quota_total", ColumnType.INTEGER),
                ColumnDef("monthly_quota_used", ColumnType.INTEGER),
                ColumnDef("purchased_quota_remaining", ColumnType.INTEGER),
                ColumnDef("quota_reset_date", ColumnType.TEXT),
                ColumnDef("additional_purchased_quota", ColumnType.INTEGER),
                ColumnDef("premium_trial_start_date", ColumnType.TEXT),
                ColumnDef("plan_id", ColumnType.TEXT),
                ColumnDef("billing_cycle", ColumnType.TEXT),
                ColumnDef("subscription_status", ColumnType.TEXT),
                ColumnDef("razorpay_subscription_id", ColumnType.TEXT),
                ColumnDef("razorpay_customer_id", ColumnType.TEXT),
                ColumnDef("current_period_end", ColumnType.TEXT),
                ColumnDef("comp_tier", ColumnType.TEXT),
                ColumnDef("comp_until", ColumnType.TEXT),
                ColumnDef("updated_at", ColumnType.TEXT),
            ),
            indexes = emptyList(),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "exchange_rates",
            viewName = "exchange_rates",
            columns = listOf(
                ColumnDef("base_currency", ColumnType.TEXT),
                ColumnDef("quote_currency", ColumnType.TEXT),
                ColumnDef("rate", ColumnType.REAL),
                ColumnDef("as_of", ColumnType.TEXT),
            ),
            indexes = listOf(
                IndexDef("by_pair", listOf(IndexColumnDef("base_currency", true, ColumnType.TEXT), IndexColumnDef("quote_currency", true, ColumnType.TEXT), IndexColumnDef("as_of", true, ColumnType.TEXT))),
            ),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "expense_item_shares",
            viewName = "expense_item_shares",
            columns = listOf(
                ColumnDef("item_id", ColumnType.TEXT),
                ColumnDef("expense_id", ColumnType.TEXT),
                ColumnDef("group_id", ColumnType.TEXT),
                ColumnDef("user_id", ColumnType.TEXT),
                ColumnDef("weight", ColumnType.INTEGER),
                ColumnDef("share_amount", ColumnType.INTEGER),
                ColumnDef("created_at", ColumnType.TEXT),
                ColumnDef("updated_at", ColumnType.TEXT),
                ColumnDef("deleted_at", ColumnType.TEXT),
            ),
            indexes = listOf(
                IndexDef("by_item", listOf(IndexColumnDef("item_id", true, ColumnType.TEXT))),
                IndexDef("by_expense", listOf(IndexColumnDef("expense_id", true, ColumnType.TEXT))),
                IndexDef("by_user", listOf(IndexColumnDef("user_id", true, ColumnType.TEXT))),
            ),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "expense_items",
            viewName = "expense_items",
            columns = listOf(
                ColumnDef("expense_id", ColumnType.TEXT),
                ColumnDef("group_id", ColumnType.TEXT),
                ColumnDef("kind", ColumnType.TEXT),
                ColumnDef("description", ColumnType.TEXT),
                ColumnDef("quantity", ColumnType.INTEGER),
                ColumnDef("unit", ColumnType.TEXT),
                ColumnDef("unit_price", ColumnType.INTEGER),
                ColumnDef("amount", ColumnType.INTEGER),
                ColumnDef("split_mode", ColumnType.TEXT),
                ColumnDef("sort", ColumnType.INTEGER),
                ColumnDef("created_at", ColumnType.TEXT),
                ColumnDef("updated_at", ColumnType.TEXT),
                ColumnDef("deleted_at", ColumnType.TEXT),
            ),
            indexes = listOf(
                IndexDef("by_expense", listOf(IndexColumnDef("expense_id", true, ColumnType.TEXT), IndexColumnDef("sort", true, ColumnType.INTEGER))),
                IndexDef("by_group", listOf(IndexColumnDef("group_id", true, ColumnType.TEXT))),
            ),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "expense_participants",
            viewName = "expense_participants",
            columns = listOf(
                ColumnDef("expense_id", ColumnType.TEXT),
                ColumnDef("group_id", ColumnType.TEXT),
                ColumnDef("user_id", ColumnType.TEXT),
                ColumnDef("paid_amount", ColumnType.INTEGER),
                ColumnDef("share_amount", ColumnType.INTEGER),
                ColumnDef("created_at", ColumnType.TEXT),
                ColumnDef("updated_at", ColumnType.TEXT),
                ColumnDef("deleted_at", ColumnType.TEXT),
            ),
            indexes = listOf(
                IndexDef("by_group", listOf(IndexColumnDef("group_id", true, ColumnType.TEXT))),
                IndexDef("by_expense", listOf(IndexColumnDef("expense_id", true, ColumnType.TEXT))),
            ),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "expense_postings",
            viewName = "expense_postings",
            columns = listOf(
                ColumnDef("user_id", ColumnType.TEXT),
                ColumnDef("expense_id", ColumnType.TEXT),
                ColumnDef("settlement_id", ColumnType.TEXT),
                ColumnDef("transaction_id", ColumnType.TEXT),
                ColumnDef("role", ColumnType.TEXT),
                ColumnDef("created_at", ColumnType.TEXT),
                ColumnDef("updated_at", ColumnType.TEXT),
                ColumnDef("deleted_at", ColumnType.TEXT),
            ),
            indexes = listOf(
                IndexDef("by_expense", listOf(IndexColumnDef("expense_id", true, ColumnType.TEXT))),
            ),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "expenses",
            viewName = "expenses",
            columns = listOf(
                ColumnDef("group_id", ColumnType.TEXT),
                ColumnDef("created_by", ColumnType.TEXT),
                ColumnDef("description", ColumnType.TEXT),
                ColumnDef("amount", ColumnType.INTEGER),
                ColumnDef("currency", ColumnType.TEXT),
                ColumnDef("occurred_at", ColumnType.TEXT),
                ColumnDef("split_mode", ColumnType.TEXT),
                ColumnDef("version", ColumnType.INTEGER),
                ColumnDef("has_items", ColumnType.INTEGER),
                ColumnDef("created_at", ColumnType.TEXT),
                ColumnDef("updated_at", ColumnType.TEXT),
                ColumnDef("deleted_at", ColumnType.TEXT),
            ),
            indexes = listOf(
                IndexDef("by_group", listOf(IndexColumnDef("group_id", true, ColumnType.TEXT), IndexColumnDef("occurred_at", true, ColumnType.TEXT))),
            ),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "failed_writes",
            viewName = "failed_writes",
            columns = listOf(
                ColumnDef("table_name", ColumnType.TEXT),
                ColumnDef("op", ColumnType.TEXT),
                ColumnDef("row_id", ColumnType.TEXT),
                ColumnDef("payload", ColumnType.TEXT),
                ColumnDef("code", ColumnType.TEXT),
                ColumnDef("message", ColumnType.TEXT),
                ColumnDef("cls", ColumnType.TEXT),
                ColumnDef("reason", ColumnType.TEXT),
                ColumnDef("attempts", ColumnType.INTEGER),
                ColumnDef("failed_at", ColumnType.TEXT),
                ColumnDef("resolved_at", ColumnType.TEXT),
                ColumnDef("resolution", ColumnType.TEXT),
            ),
            indexes = listOf(
                IndexDef("by_failed", listOf(IndexColumnDef("failed_at", true, ColumnType.TEXT))),
            ),
            localOnly = true,
            insertOnly = false,
        ),
        TableDef(
            name = "goal_allocations",
            viewName = "goal_allocations",
            columns = listOf(
                ColumnDef("user_id", ColumnType.TEXT),
                ColumnDef("goal_id", ColumnType.TEXT),
                ColumnDef("source_account_id", ColumnType.TEXT),
                ColumnDef("amount_blocked", ColumnType.INTEGER),
                ColumnDef("created_at", ColumnType.TEXT),
                ColumnDef("updated_at", ColumnType.TEXT),
                ColumnDef("deleted_at", ColumnType.TEXT),
            ),
            indexes = emptyList(),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "goals",
            viewName = "goals",
            columns = listOf(
                ColumnDef("user_id", ColumnType.TEXT),
                ColumnDef("name", ColumnType.TEXT),
                ColumnDef("target_amount", ColumnType.INTEGER),
                ColumnDef("currency", ColumnType.TEXT),
                ColumnDef("priority", ColumnType.INTEGER),
                ColumnDef("is_emergency_fund", ColumnType.INTEGER),
                ColumnDef("target_date", ColumnType.TEXT),
                ColumnDef("alert_time_utc", ColumnType.TEXT),
                ColumnDef("created_at", ColumnType.TEXT),
                ColumnDef("updated_at", ColumnType.TEXT),
                ColumnDef("deleted_at", ColumnType.TEXT),
            ),
            indexes = emptyList(),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "holdings",
            viewName = "holdings",
            columns = listOf(
                ColumnDef("user_id", ColumnType.TEXT),
                ColumnDef("account_id", ColumnType.TEXT),
                ColumnDef("symbol", ColumnType.TEXT),
                ColumnDef("exchange", ColumnType.TEXT),
                ColumnDef("quantity", ColumnType.REAL),
                ColumnDef("avg_cost", ColumnType.INTEGER),
                ColumnDef("currency", ColumnType.TEXT),
                ColumnDef("auto_fetch", ColumnType.INTEGER),
                ColumnDef("instrument_type", ColumnType.TEXT),
                ColumnDef("off_list", ColumnType.INTEGER),
                ColumnDef("name", ColumnType.TEXT),
                ColumnDef("asset_class", ColumnType.TEXT),
                ColumnDef("current_value", ColumnType.INTEGER),
                ColumnDef("annual_rate", ColumnType.REAL),
                ColumnDef("maturity_date", ColumnType.TEXT),
                ColumnDef("source_account_id", ColumnType.TEXT),
                ColumnDef("planned_id", ColumnType.TEXT),
                ColumnDef("created_at", ColumnType.TEXT),
                ColumnDef("updated_at", ColumnType.TEXT),
                ColumnDef("deleted_at", ColumnType.TEXT),
            ),
            indexes = emptyList(),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "labels",
            viewName = "labels",
            columns = listOf(
                ColumnDef("user_id", ColumnType.TEXT),
                ColumnDef("name", ColumnType.TEXT),
                ColumnDef("color", ColumnType.TEXT),
                ColumnDef("created_at", ColumnType.TEXT),
                ColumnDef("updated_at", ColumnType.TEXT),
                ColumnDef("deleted_at", ColumnType.TEXT),
            ),
            indexes = emptyList(),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "loans",
            viewName = "loans",
            columns = listOf(
                ColumnDef("user_id", ColumnType.TEXT),
                ColumnDef("lender", ColumnType.TEXT),
                ColumnDef("principal", ColumnType.INTEGER),
                ColumnDef("currency", ColumnType.TEXT),
                ColumnDef("interest_rate", ColumnType.REAL),
                ColumnDef("tenure_months", ColumnType.INTEGER),
                ColumnDef("emi_amount", ColumnType.INTEGER),
                ColumnDef("start_date", ColumnType.TEXT),
                ColumnDef("emis_paid", ColumnType.INTEGER),
                ColumnDef("emi_payments", ColumnType.TEXT),
                ColumnDef("emi_due_day", ColumnType.INTEGER),
                ColumnDef("auto_mark_paid", ColumnType.INTEGER),
                ColumnDef("rate_type", ColumnType.TEXT),
                ColumnDef("funding_account_id", ColumnType.TEXT),
                ColumnDef("emi_amounts", ColumnType.TEXT),
                ColumnDef("alert_time_utc", ColumnType.TEXT),
                ColumnDef("created_at", ColumnType.TEXT),
                ColumnDef("updated_at", ColumnType.TEXT),
                ColumnDef("deleted_at", ColumnType.TEXT),
            ),
            indexes = emptyList(),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "market_dividends",
            viewName = "market_dividends",
            columns = listOf(
                ColumnDef("symbol", ColumnType.TEXT),
                ColumnDef("exchange", ColumnType.TEXT),
                ColumnDef("ex_date", ColumnType.TEXT),
                ColumnDef("pay_date", ColumnType.TEXT),
                ColumnDef("amount", ColumnType.INTEGER),
                ColumnDef("currency", ColumnType.TEXT),
                ColumnDef("updated_at", ColumnType.TEXT),
            ),
            indexes = listOf(
                IndexDef("by_symbol", listOf(IndexColumnDef("symbol", true, ColumnType.TEXT))),
            ),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "market_overview",
            viewName = "market_overview",
            columns = listOf(
                ColumnDef("symbol", ColumnType.TEXT),
                ColumnDef("exchange", ColumnType.TEXT),
                ColumnDef("name", ColumnType.TEXT),
                ColumnDef("sector", ColumnType.TEXT),
                ColumnDef("industry", ColumnType.TEXT),
                ColumnDef("currency", ColumnType.TEXT),
                ColumnDef("pe", ColumnType.REAL),
                ColumnDef("eps", ColumnType.REAL),
                ColumnDef("dividend_yield", ColumnType.REAL),
                ColumnDef("dividend_per_share", ColumnType.REAL),
                ColumnDef("ex_dividend_date", ColumnType.TEXT),
                ColumnDef("updated_at", ColumnType.TEXT),
            ),
            indexes = listOf(
                IndexDef("by_symbol", listOf(IndexColumnDef("symbol", true, ColumnType.TEXT))),
            ),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "market_quotes",
            viewName = "market_quotes",
            columns = listOf(
                ColumnDef("symbol", ColumnType.TEXT),
                ColumnDef("exchange", ColumnType.TEXT),
                ColumnDef("price", ColumnType.INTEGER),
                ColumnDef("currency", ColumnType.TEXT),
                ColumnDef("change_abs", ColumnType.INTEGER),
                ColumnDef("change_pct", ColumnType.REAL),
                ColumnDef("as_of", ColumnType.TEXT),
                ColumnDef("updated_at", ColumnType.TEXT),
            ),
            indexes = listOf(
                IndexDef("by_symbol", listOf(IndexColumnDef("symbol", true, ColumnType.TEXT))),
            ),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "notification_prefs",
            viewName = "notification_prefs",
            columns = listOf(
                ColumnDef("user_id", ColumnType.TEXT),
                ColumnDef("push_enabled", ColumnType.INTEGER),
                ColumnDef("emi_due", ColumnType.INTEGER),
                ColumnDef("budget", ColumnType.INTEGER),
                ColumnDef("low_balance", ColumnType.INTEGER),
                ColumnDef("outlier", ColumnType.INTEGER),
                ColumnDef("group_invite", ColumnType.INTEGER),
                ColumnDef("group_expense", ColumnType.INTEGER),
                ColumnDef("low_balance_threshold", ColumnType.INTEGER),
                ColumnDef("emi_lead_days", ColumnType.INTEGER),
                ColumnDef("created_at", ColumnType.TEXT),
                ColumnDef("updated_at", ColumnType.TEXT),
                ColumnDef("deleted_at", ColumnType.TEXT),
            ),
            indexes = emptyList(),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "notifications",
            viewName = "notifications",
            columns = listOf(
                ColumnDef("user_id", ColumnType.TEXT),
                ColumnDef("kind", ColumnType.TEXT),
                ColumnDef("title", ColumnType.TEXT),
                ColumnDef("body", ColumnType.TEXT),
                ColumnDef("severity", ColumnType.TEXT),
                ColumnDef("href", ColumnType.TEXT),
                ColumnDef("data", ColumnType.TEXT),
                ColumnDef("dedupe_key", ColumnType.TEXT),
                ColumnDef("read_at", ColumnType.TEXT),
                ColumnDef("pushed_at", ColumnType.TEXT),
                ColumnDef("created_at", ColumnType.TEXT),
                ColumnDef("updated_at", ColumnType.TEXT),
                ColumnDef("deleted_at", ColumnType.TEXT),
            ),
            indexes = listOf(
                IndexDef("by_user_read", listOf(IndexColumnDef("user_id", true, ColumnType.TEXT), IndexColumnDef("read_at", true, ColumnType.TEXT))),
            ),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "payment_handle_disclosures",
            viewName = "payment_handle_disclosures",
            columns = listOf(
                ColumnDef("owner_user_id", ColumnType.TEXT),
                ColumnDef("viewer_user_id", ColumnType.TEXT),
                ColumnDef("group_id", ColumnType.TEXT),
                ColumnDef("created_at", ColumnType.TEXT),
            ),
            indexes = listOf(
                IndexDef("by_created", listOf(IndexColumnDef("created_at", true, ColumnType.TEXT))),
            ),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "payment_methods",
            viewName = "payment_methods",
            columns = listOf(
                ColumnDef("label", ColumnType.TEXT),
                ColumnDef("sort", ColumnType.INTEGER),
            ),
            indexes = emptyList(),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "payments",
            viewName = "payments",
            columns = listOf(
                ColumnDef("user_id", ColumnType.TEXT),
                ColumnDef("kind", ColumnType.TEXT),
                ColumnDef("razorpay_order_id", ColumnType.TEXT),
                ColumnDef("razorpay_payment_id", ColumnType.TEXT),
                ColumnDef("razorpay_subscription_id", ColumnType.TEXT),
                ColumnDef("amount", ColumnType.INTEGER),
                ColumnDef("currency", ColumnType.TEXT),
                ColumnDef("status", ColumnType.TEXT),
                ColumnDef("credits_added", ColumnType.INTEGER),
                ColumnDef("created_at", ColumnType.TEXT),
                ColumnDef("updated_at", ColumnType.TEXT),
            ),
            indexes = listOf(
                IndexDef("by_user", listOf(IndexColumnDef("user_id", true, ColumnType.TEXT), IndexColumnDef("created_at", true, ColumnType.TEXT))),
            ),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "periods",
            viewName = "periods",
            columns = listOf(
                ColumnDef("label", ColumnType.TEXT),
                ColumnDef("sort", ColumnType.INTEGER),
            ),
            indexes = emptyList(),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "planned_cashflow",
            viewName = "planned_cashflow",
            columns = listOf(
                ColumnDef("user_id", ColumnType.TEXT),
                ColumnDef("name", ColumnType.TEXT),
                ColumnDef("direction", ColumnType.TEXT),
                ColumnDef("bucket", ColumnType.TEXT),
                ColumnDef("amount", ColumnType.INTEGER),
                ColumnDef("currency", ColumnType.TEXT),
                ColumnDef("frequency", ColumnType.TEXT),
                ColumnDef("timeframe", ColumnType.TEXT),
                ColumnDef("next_due", ColumnType.TEXT),
                ColumnDef("expected_return", ColumnType.INTEGER),
                ColumnDef("category_id", ColumnType.TEXT),
                ColumnDef("account_id", ColumnType.TEXT),
                ColumnDef("notes", ColumnType.TEXT),
                ColumnDef("is_active", ColumnType.INTEGER),
                ColumnDef("created_at", ColumnType.TEXT),
                ColumnDef("updated_at", ColumnType.TEXT),
                ColumnDef("deleted_at", ColumnType.TEXT),
            ),
            indexes = listOf(
                IndexDef("by_user", listOf(IndexColumnDef("user_id", true, ColumnType.TEXT), IndexColumnDef("direction", true, ColumnType.TEXT))),
            ),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "profiles",
            viewName = "profiles",
            columns = listOf(
                ColumnDef("base_currency", ColumnType.TEXT),
                ColumnDef("locale", ColumnType.TEXT),
                ColumnDef("rate_mode", ColumnType.TEXT),
                ColumnDef("theme", ColumnType.TEXT),
                ColumnDef("display_name", ColumnType.TEXT),
                ColumnDef("email", ColumnType.TEXT),
                ColumnDef("gender", ColumnType.TEXT),
                ColumnDef("country", ColumnType.TEXT),
                ColumnDef("created_at", ColumnType.TEXT),
                ColumnDef("updated_at", ColumnType.TEXT),
            ),
            indexes = emptyList(),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "promo_redemptions",
            viewName = "promo_redemptions",
            columns = listOf(
                ColumnDef("code", ColumnType.TEXT),
                ColumnDef("user_id", ColumnType.TEXT),
                ColumnDef("applied_until", ColumnType.TEXT),
                ColumnDef("redeemed_at", ColumnType.TEXT),
            ),
            indexes = emptyList(),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "rate_modes",
            viewName = "rate_modes",
            columns = listOf(
                ColumnDef("label", ColumnType.TEXT),
                ColumnDef("sort", ColumnType.INTEGER),
            ),
            indexes = emptyList(),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "receipt_scans",
            viewName = "receipt_scans",
            columns = listOf(
                ColumnDef("user_id", ColumnType.TEXT),
                ColumnDef("source", ColumnType.TEXT),
                ColumnDef("engine", ColumnType.TEXT),
                ColumnDef("merchant", ColumnType.TEXT),
                ColumnDef("occurred_at", ColumnType.TEXT),
                ColumnDef("currency", ColumnType.TEXT),
                ColumnDef("subtotal", ColumnType.INTEGER),
                ColumnDef("tax", ColumnType.INTEGER),
                ColumnDef("service_charge", ColumnType.INTEGER),
                ColumnDef("tip", ColumnType.INTEGER),
                ColumnDef("discount", ColumnType.INTEGER),
                ColumnDef("total", ColumnType.INTEGER),
                ColumnDef("confidence", ColumnType.INTEGER),
                ColumnDef("raw_text", ColumnType.TEXT),
                ColumnDef("parsed_json", ColumnType.TEXT),
                ColumnDef("transaction_id", ColumnType.TEXT),
                ColumnDef("expense_id", ColumnType.TEXT),
                ColumnDef("image_path", ColumnType.TEXT),
                ColumnDef("created_at", ColumnType.TEXT),
                ColumnDef("updated_at", ColumnType.TEXT),
                ColumnDef("deleted_at", ColumnType.TEXT),
            ),
            indexes = listOf(
                IndexDef("by_created", listOf(IndexColumnDef("created_at", true, ColumnType.TEXT))),
                IndexDef("by_txn", listOf(IndexColumnDef("transaction_id", true, ColumnType.TEXT))),
            ),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "recurring_commitments",
            viewName = "recurring_commitments",
            columns = listOf(
                ColumnDef("user_id", ColumnType.TEXT),
                ColumnDef("kind", ColumnType.TEXT),
                ColumnDef("amount", ColumnType.INTEGER),
                ColumnDef("currency", ColumnType.TEXT),
                ColumnDef("frequency", ColumnType.TEXT),
                ColumnDef("next_due", ColumnType.TEXT),
                ColumnDef("category_id", ColumnType.TEXT),
                ColumnDef("account_id", ColumnType.TEXT),
                ColumnDef("loan_id", ColumnType.TEXT),
                ColumnDef("subscription_id", ColumnType.TEXT),
                ColumnDef("created_at", ColumnType.TEXT),
                ColumnDef("updated_at", ColumnType.TEXT),
                ColumnDef("deleted_at", ColumnType.TEXT),
            ),
            indexes = emptyList(),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "recurring_groups",
            viewName = "recurring_groups",
            columns = listOf(
                ColumnDef("user_id", ColumnType.TEXT),
                ColumnDef("name", ColumnType.TEXT),
                ColumnDef("direction", ColumnType.TEXT),
                ColumnDef("icon", ColumnType.TEXT),
                ColumnDef("color", ColumnType.TEXT),
                ColumnDef("sort", ColumnType.INTEGER),
                ColumnDef("is_system", ColumnType.INTEGER),
                ColumnDef("created_at", ColumnType.TEXT),
                ColumnDef("updated_at", ColumnType.TEXT),
                ColumnDef("deleted_at", ColumnType.TEXT),
            ),
            indexes = listOf(
                IndexDef("by_user", listOf(IndexColumnDef("user_id", true, ColumnType.TEXT), IndexColumnDef("direction", true, ColumnType.TEXT))),
            ),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "recurring_rules",
            viewName = "recurring_rules",
            columns = listOf(
                ColumnDef("user_id", ColumnType.TEXT),
                ColumnDef("template_id", ColumnType.TEXT),
                ColumnDef("frequency", ColumnType.TEXT),
                ColumnDef("interval_count", ColumnType.INTEGER),
                ColumnDef("next_due", ColumnType.TEXT),
                ColumnDef("last_generated", ColumnType.TEXT),
                ColumnDef("auto_post", ColumnType.INTEGER),
                ColumnDef("active", ColumnType.INTEGER),
                ColumnDef("alert_time_utc", ColumnType.TEXT),
                ColumnDef("created_at", ColumnType.TEXT),
                ColumnDef("updated_at", ColumnType.TEXT),
                ColumnDef("deleted_at", ColumnType.TEXT),
            ),
            indexes = listOf(
                IndexDef("by_user", listOf(IndexColumnDef("user_id", true, ColumnType.TEXT), IndexColumnDef("next_due", true, ColumnType.TEXT))),
            ),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "security_audit",
            viewName = "security_audit",
            columns = listOf(
                ColumnDef("actor", ColumnType.TEXT),
                ColumnDef("action", ColumnType.TEXT),
                ColumnDef("subject_user", ColumnType.TEXT),
                ColumnDef("grant_id", ColumnType.TEXT),
                ColumnDef("detail", ColumnType.TEXT),
                ColumnDef("prev_hash", ColumnType.TEXT),
                ColumnDef("row_hash", ColumnType.TEXT),
                ColumnDef("created_at", ColumnType.TEXT),
            ),
            indexes = emptyList(),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "settlements",
            viewName = "settlements",
            columns = listOf(
                ColumnDef("group_id", ColumnType.TEXT),
                ColumnDef("from_user", ColumnType.TEXT),
                ColumnDef("to_user", ColumnType.TEXT),
                ColumnDef("amount", ColumnType.INTEGER),
                ColumnDef("currency", ColumnType.TEXT),
                ColumnDef("method", ColumnType.TEXT),
                ColumnDef("note", ColumnType.TEXT),
                ColumnDef("settled_at", ColumnType.TEXT),
                ColumnDef("created_by", ColumnType.TEXT),
                ColumnDef("status", ColumnType.TEXT),
                ColumnDef("confirmed_at", ColumnType.TEXT),
                ColumnDef("confirmed_by", ColumnType.TEXT),
                ColumnDef("upi_ref", ColumnType.TEXT),
                ColumnDef("created_at", ColumnType.TEXT),
                ColumnDef("updated_at", ColumnType.TEXT),
                ColumnDef("deleted_at", ColumnType.TEXT),
            ),
            indexes = listOf(
                IndexDef("by_group", listOf(IndexColumnDef("group_id", true, ColumnType.TEXT))),
                IndexDef("by_status", listOf(IndexColumnDef("status", true, ColumnType.TEXT))),
            ),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "split_group_members",
            viewName = "split_group_members",
            columns = listOf(
                ColumnDef("group_id", ColumnType.TEXT),
                ColumnDef("user_id", ColumnType.TEXT),
                ColumnDef("role", ColumnType.TEXT),
                ColumnDef("created_at", ColumnType.TEXT),
                ColumnDef("updated_at", ColumnType.TEXT),
                ColumnDef("deleted_at", ColumnType.TEXT),
            ),
            indexes = listOf(
                IndexDef("by_group", listOf(IndexColumnDef("group_id", true, ColumnType.TEXT))),
                IndexDef("by_user", listOf(IndexColumnDef("user_id", true, ColumnType.TEXT))),
            ),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "split_groups",
            viewName = "split_groups",
            columns = listOf(
                ColumnDef("created_by", ColumnType.TEXT),
                ColumnDef("name", ColumnType.TEXT),
                ColumnDef("kind", ColumnType.TEXT),
                ColumnDef("is_direct", ColumnType.INTEGER),
                ColumnDef("start_date", ColumnType.TEXT),
                ColumnDef("end_date", ColumnType.TEXT),
                ColumnDef("auto_split", ColumnType.INTEGER),
                ColumnDef("default_mode", ColumnType.TEXT),
                ColumnDef("currency", ColumnType.TEXT),
                ColumnDef("archived", ColumnType.INTEGER),
                ColumnDef("created_at", ColumnType.TEXT),
                ColumnDef("updated_at", ColumnType.TEXT),
                ColumnDef("deleted_at", ColumnType.TEXT),
            ),
            indexes = emptyList(),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "split_invitations",
            viewName = "split_invitations",
            columns = listOf(
                ColumnDef("group_id", ColumnType.TEXT),
                ColumnDef("inviter", ColumnType.TEXT),
                ColumnDef("invitee_email", ColumnType.TEXT),
                ColumnDef("token", ColumnType.TEXT),
                ColumnDef("status", ColumnType.TEXT),
                ColumnDef("accepted_by", ColumnType.TEXT),
                ColumnDef("created_at", ColumnType.TEXT),
                ColumnDef("updated_at", ColumnType.TEXT),
                ColumnDef("expires_at", ColumnType.TEXT),
            ),
            indexes = emptyList(),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "subscriptions",
            viewName = "subscriptions",
            columns = listOf(
                ColumnDef("user_id", ColumnType.TEXT),
                ColumnDef("name", ColumnType.TEXT),
                ColumnDef("amount", ColumnType.INTEGER),
                ColumnDef("currency", ColumnType.TEXT),
                ColumnDef("billing_cycle", ColumnType.TEXT),
                ColumnDef("purchased_on", ColumnType.TEXT),
                ColumnDef("next_renewal", ColumnType.TEXT),
                ColumnDef("category_id", ColumnType.TEXT),
                ColumnDef("is_active", ColumnType.INTEGER),
                ColumnDef("created_at", ColumnType.TEXT),
                ColumnDef("updated_at", ColumnType.TEXT),
                ColumnDef("deleted_at", ColumnType.TEXT),
            ),
            indexes = emptyList(),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "support_grants",
            viewName = "support_grants",
            columns = listOf(
                ColumnDef("user_id", ColumnType.TEXT),
                ColumnDef("scope", ColumnType.TEXT),
                ColumnDef("wrapped_dek_for_support", ColumnType.TEXT),
                ColumnDef("signature", ColumnType.TEXT),
                ColumnDef("expires_at", ColumnType.TEXT),
                ColumnDef("revoked_at", ColumnType.TEXT),
                ColumnDef("created_at", ColumnType.TEXT),
            ),
            indexes = emptyList(),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "sync_attempts",
            viewName = "sync_attempts",
            columns = listOf(
                ColumnDef("attempts", ColumnType.INTEGER),
                ColumnDef("last_code", ColumnType.TEXT),
                ColumnDef("updated_at", ColumnType.TEXT),
            ),
            indexes = emptyList(),
            localOnly = true,
            insertOnly = false,
        ),
        TableDef(
            name = "tiers",
            viewName = "tiers",
            columns = listOf(
                ColumnDef("label", ColumnType.TEXT),
                ColumnDef("sort", ColumnType.INTEGER),
            ),
            indexes = emptyList(),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "transaction_audit",
            viewName = "transaction_audit",
            columns = listOf(
                ColumnDef("user_id", ColumnType.TEXT),
                ColumnDef("transaction_id", ColumnType.TEXT),
                ColumnDef("action", ColumnType.TEXT),
                ColumnDef("changes", ColumnType.TEXT),
                ColumnDef("created_at", ColumnType.TEXT),
            ),
            indexes = listOf(
                IndexDef("by_txn", listOf(IndexColumnDef("transaction_id", true, ColumnType.TEXT))),
            ),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "transaction_items",
            viewName = "transaction_items",
            columns = listOf(
                ColumnDef("user_id", ColumnType.TEXT),
                ColumnDef("transaction_id", ColumnType.TEXT),
                ColumnDef("description", ColumnType.TEXT),
                ColumnDef("amount", ColumnType.INTEGER),
                ColumnDef("created_at", ColumnType.TEXT),
                ColumnDef("updated_at", ColumnType.TEXT),
                ColumnDef("deleted_at", ColumnType.TEXT),
            ),
            indexes = listOf(
                IndexDef("by_txn", listOf(IndexColumnDef("transaction_id", true, ColumnType.TEXT))),
            ),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "transaction_labels",
            viewName = "transaction_labels",
            columns = listOf(
                ColumnDef("user_id", ColumnType.TEXT),
                ColumnDef("transaction_id", ColumnType.TEXT),
                ColumnDef("label_id", ColumnType.TEXT),
                ColumnDef("created_at", ColumnType.TEXT),
            ),
            indexes = listOf(
                IndexDef("by_txn", listOf(IndexColumnDef("transaction_id", true, ColumnType.TEXT))),
                IndexDef("by_label", listOf(IndexColumnDef("label_id", true, ColumnType.TEXT))),
            ),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "transaction_templates",
            viewName = "transaction_templates",
            columns = listOf(
                ColumnDef("user_id", ColumnType.TEXT),
                ColumnDef("name", ColumnType.TEXT),
                ColumnDef("type", ColumnType.TEXT),
                ColumnDef("amount", ColumnType.INTEGER),
                ColumnDef("currency", ColumnType.TEXT),
                ColumnDef("account_id", ColumnType.TEXT),
                ColumnDef("to_account_id", ColumnType.TEXT),
                ColumnDef("category_id", ColumnType.TEXT),
                ColumnDef("description", ColumnType.TEXT),
                ColumnDef("note", ColumnType.TEXT),
                ColumnDef("payment_method", ColumnType.TEXT),
                ColumnDef("labels", ColumnType.TEXT),
                ColumnDef("split_group_id", ColumnType.TEXT),
                ColumnDef("split_mode", ColumnType.TEXT),
                ColumnDef("sort", ColumnType.INTEGER),
                ColumnDef("group_id", ColumnType.TEXT),
                ColumnDef("created_at", ColumnType.TEXT),
                ColumnDef("updated_at", ColumnType.TEXT),
                ColumnDef("deleted_at", ColumnType.TEXT),
            ),
            indexes = listOf(
                IndexDef("by_user", listOf(IndexColumnDef("user_id", true, ColumnType.TEXT))),
            ),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "transaction_types",
            viewName = "transaction_types",
            columns = listOf(
                ColumnDef("label", ColumnType.TEXT),
                ColumnDef("sort", ColumnType.INTEGER),
            ),
            indexes = emptyList(),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "transactions",
            viewName = "transactions",
            columns = listOf(
                ColumnDef("user_id", ColumnType.TEXT),
                ColumnDef("account_id", ColumnType.TEXT),
                ColumnDef("type", ColumnType.TEXT),
                ColumnDef("amount", ColumnType.INTEGER),
                ColumnDef("currency", ColumnType.TEXT),
                ColumnDef("category_id", ColumnType.TEXT),
                ColumnDef("note", ColumnType.TEXT),
                ColumnDef("description", ColumnType.TEXT),
                ColumnDef("payment_method", ColumnType.TEXT),
                ColumnDef("occurred_at", ColumnType.TEXT),
                ColumnDef("transfer_group_id", ColumnType.TEXT),
                ColumnDef("to_account_id", ColumnType.TEXT),
                ColumnDef("to_amount", ColumnType.INTEGER),
                ColumnDef("fx_rate", ColumnType.REAL),
                ColumnDef("created_at", ColumnType.TEXT),
                ColumnDef("updated_at", ColumnType.TEXT),
                ColumnDef("deleted_at", ColumnType.TEXT),
            ),
            indexes = listOf(
                IndexDef("by_account", listOf(IndexColumnDef("account_id", true, ColumnType.TEXT), IndexColumnDef("occurred_at", true, ColumnType.TEXT))),
            ),
            localOnly = false,
            insertOnly = false,
        ),
        TableDef(
            name = "user_keys",
            viewName = "user_keys",
            columns = listOf(
                ColumnDef("user_id", ColumnType.TEXT),
                ColumnDef("salt", ColumnType.TEXT),
                ColumnDef("wrapped_dek_passphrase", ColumnType.TEXT),
                ColumnDef("wrapped_dek_recovery", ColumnType.TEXT),
                ColumnDef("signing_public_jwk", ColumnType.TEXT),
                ColumnDef("wrapped_signing_private", ColumnType.TEXT),
                ColumnDef("created_at", ColumnType.TEXT),
                ColumnDef("updated_at", ColumnType.TEXT),
            ),
            indexes = emptyList(),
            localOnly = false,
            insertOnly = false,
        ),
    )

    val byName: Map<String, TableDef> = tables.associateBy { it.name }
}
