package com.sanvya.app.domain.categorize

// GENERATED FILE - do not hand-edit.
// Source: apps/web/src/categorize/seeds.ts (SEED_RULES)
//         apps/web/src/categorize/normalize.ts (STOP_WORDS, NOISE_TOKENS)
// Regenerate with: node tools/parity/generate-category-seeds.mjs

/**
 * The auto-categoriser's cold-start tables, exactly as web writes them.
 * 
 * SEED_RULES maps a keyword to a category NAME, not an id -- the ids are the
 * user's own and are resolved at runtime by buildSeedMap(). NOISE_TOKENS and
 * STOP_WORDS decide which tokens survive normalisation at all, which is why
 * they are generated too: one platform missing a bank code silently changes
 * what every statement row categorises as.
 */
object CategorySeeds {
    /** keyword -> category NAME. Insertion order is web's, and buildSeedList depends on it for tie-breaks. */
    val SEED_RULES: Map<String, String> = linkedMapOf(
        "uber" to "Transport",
        "ola" to "Transport",
        "lyft" to "Transport",
        "metro" to "Transport",
        "train" to "Transport",
        "bus" to "Transport",
        "flight" to "Transport",
        "indigo" to "Transport",
        "airasia" to "Transport",
        "fuel" to "Transport",
        "petrol" to "Transport",
        "shell" to "Transport",
        "swiggy" to "Food & Dining",
        "zomato" to "Food & Dining",
        "ubereats" to "Food & Dining",
        "doordash" to "Food & Dining",
        "starbucks" to "Food & Dining",
        "mcdonalds" to "Food & Dining",
        "kfc" to "Food & Dining",
        "dominos" to "Food & Dining",
        "restaurant" to "Food & Dining",
        "cafe" to "Food & Dining",
        "coffee" to "Food & Dining",
        "tea" to "Food & Dining",
        "lunch" to "Food & Dining",
        "dinner" to "Food & Dining",
        "breakfast" to "Food & Dining",
        "pizza" to "Food & Dining",
        "burger" to "Food & Dining",
        "meal" to "Food & Dining",
        "snacks" to "Food & Dining",
        "chocolate" to "Food & Dining",
        "icecream" to "Food & Dining",
        "blinkit" to "Groceries",
        "zepto" to "Groceries",
        "instamart" to "Groceries",
        "bigbasket" to "Groceries",
        "dmart" to "Groceries",
        "whole foods" to "Groceries",
        "walmart" to "Groceries",
        "target" to "Groceries",
        "grocery" to "Groceries",
        "groceries" to "Groceries",
        "milk" to "Groceries",
        "bread" to "Groceries",
        "eggs" to "Groceries",
        "vegetables" to "Groceries",
        "veggies" to "Groceries",
        "fruits" to "Groceries",
        "rice" to "Groceries",
        "oil" to "Groceries",
        "sugar" to "Groceries",
        "amazon" to "Shopping",
        "flipkart" to "Shopping",
        "myntra" to "Shopping",
        "ajio" to "Shopping",
        "zara" to "Shopping",
        "h&m" to "Shopping",
        "shoes" to "Shopping",
        "shirt" to "Shopping",
        "tshirt" to "Shopping",
        "clothes" to "Shopping",
        "dress" to "Shopping",
        "jeans" to "Shopping",
        "jacket" to "Shopping",
        "bag" to "Shopping",
        "watch" to "Shopping",
        "medicine" to "Health",
        "pharmacy" to "Health",
        "chemist" to "Health",
        "doctor" to "Health",
        "hospital" to "Health",
        "clinic" to "Health",
        "gym" to "Health",
        "salon" to "Personal Care",
        "haircut" to "Personal Care",
        "spa" to "Personal Care",
        "netflix" to "Subscriptions",
        "spotify" to "Subscriptions",
        "youtube" to "Subscriptions",
        "prime video" to "Subscriptions",
        "disney" to "Subscriptions",
        "apple" to "Subscriptions",
        "google" to "Subscriptions",
        "steam" to "Entertainment",
        "movie" to "Entertainment",
        "rent" to "Housing",
        "electricity" to "Utilities",
        "water" to "Utilities",
        "wifi" to "Utilities",
        "internet" to "Utilities",
        "airtel" to "Utilities",
        "jio" to "Utilities",
        "swiggyinstamart" to "Groceries",
        "eatfit" to "Food & Dining",
        "faasos" to "Food & Dining",
        "behrouz" to "Food & Dining",
        "chaayos" to "Food & Dining",
        "haldiram" to "Food & Dining",
        "barbeque" to "Food & Dining",
        "biryani" to "Food & Dining",
        "rapido" to "Transport",
        "irctc" to "Transport",
        "redbus" to "Transport",
        "makemytrip" to "Transport",
        "goibibo" to "Transport",
        "ixigo" to "Transport",
        "fastag" to "Transport",
        "hpcl" to "Transport",
        "bpcl" to "Transport",
        "ioc" to "Transport",
        "indianoil" to "Transport",
        "uberride" to "Transport",
        "parking" to "Transport",
        "toll" to "Transport",
        "bbnow" to "Groceries",
        "jiomart" to "Groceries",
        "reliancefresh" to "Groceries",
        "moreretail" to "Groceries",
        "naturebasket" to "Groceries",
        "licious" to "Groceries",
        "meesho" to "Shopping",
        "nykaa" to "Shopping",
        "tatacliq" to "Shopping",
        "snapdeal" to "Shopping",
        "croma" to "Shopping",
        "reliancedigital" to "Shopping",
        "decathlon" to "Shopping",
        "ikea" to "Shopping",
        "lenskart" to "Shopping",
        "firstcry" to "Shopping",
        "pharmeasy" to "Health",
        "netmeds" to "Health",
        "apollo" to "Health",
        "onemg" to "Health",
        "tata1mg" to "Health",
        "practo" to "Health",
        "cultfit" to "Health",
        "hotstar" to "Subscriptions",
        "sonyliv" to "Subscriptions",
        "zee5" to "Subscriptions",
        "jiocinema" to "Subscriptions",
        "audible" to "Subscriptions",
        "youtubepremium" to "Subscriptions",
        "googleone" to "Subscriptions",
        "icloud" to "Subscriptions",
        "openai" to "Subscriptions",
        "chatgpt" to "Subscriptions",
        "bookmyshow" to "Entertainment",
        "pvr" to "Entertainment",
        "inox" to "Entertainment",
        "vodafone" to "Utilities",
        "vi" to "Utilities",
        "bsnl" to "Utilities",
        "tataplay" to "Utilities",
        "actfibernet" to "Utilities",
        "adani" to "Utilities",
        "tatapower" to "Utilities",
        "bescom" to "Utilities",
        "mseb" to "Utilities",
        "gas" to "Utilities",
        "recharge" to "Utilities",
        "broadband" to "Utilities",
        "zerodha" to "Investments",
        "groww" to "Investments",
        "upstox" to "Investments",
        "coin" to "Investments",
        "kuvera" to "Investments",
        "indmoney" to "Investments",
        "lic" to "Insurance",
        "policybazaar" to "Insurance",
        "insurance" to "Insurance",
        "premium" to "Insurance",
        "udemy" to "Education",
        "coursera" to "Education",
        "unacademy" to "Education",
        "byjus" to "Education",
        "tuition" to "Education",
        "school" to "Education",
        "college" to "Education",
        "course" to "Education",
        "salary" to "Salary",
        "paycheck" to "Salary",
        "bonus" to "Bonus",
        "dividend" to "Dividends",
        "refund" to "Refunds",
    )

    val STOP_WORDS: Set<String> = setOf(
        "the",
        "and",
        "or",
        "to",
        "for",
        "in",
        "on",
        "at",
        "with",
        "a",
        "an",
        "is",
        "of",
    )

    val NOISE_TOKENS: Set<String> = setOf(
        "upi",
        "imps",
        "neft",
        "rtgs",
        "ach",
        "ecs",
        "pos",
        "atm",
        "emi",
        "nach",
        "vps",
        "mmt",
        "ift",
        "inb",
        "chq",
        "cheque",
        "clg",
        "int",
        "intl",
        "txn",
        "trf",
        "transfer",
        "tfr",
        "payment",
        "paytm",
        "gpay",
        "phonepe",
        "bhim",
        "razorpay",
        "billdesk",
        "payu",
        "dr",
        "cr",
        "debit",
        "credit",
        "debited",
        "credited",
        "paid",
        "recd",
        "received",
        "rev",
        "reversal",
        "refund",
        "charge",
        "charges",
        "fee",
        "gst",
        "tax",
        "hdfc",
        "hdfcbank",
        "icic",
        "icici",
        "sbin",
        "sbi",
        "axis",
        "axisbank",
        "kkbk",
        "kotak",
        "yesb",
        "pnb",
        "boi",
        "cnrb",
        "canara",
        "utib",
        "idfb",
        "idfc",
        "fdrl",
        "federal",
        "indb",
        "indus",
        "indusind",
        "barb",
        "baroda",
        "ubin",
        "union",
        "bank",
        "ybl",
        "okhdfcbank",
        "okicici",
        "oksbi",
        "okaxis",
        "apl",
        "ibl",
        "axl",
        "paytmqr",
        "waaxis",
        "wahdfcbank",
        "yapl",
        "airtel",
        "freecharge",
        "jupiteraxis",
        "fam",
        "ref",
        "refno",
        "no",
        "id",
        "num",
        "number",
        "acct",
        "account",
        "ac",
        "info",
        "rrn",
        "www",
        "com",
        "in",
        "ltd",
        "limited",
        "pvt",
        "private",
        "india",
        "online",
        "order",
        "purchase",
        "spent",
        "transaction",
        "vpa",
        "collect",
        "req",
        "mandate",
        "autopay",
    )
}
