package com.sanvya.app.domain.suggestions

import com.sanvya.app.domain.vectors.FunctionRegistry
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.boolean
import kotlinx.serialization.json.int
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive

// Wires Suggestions.kt into FunctionRegistry.
//
// The corpus is GENERATED by running web's own `@sanvya/suggestions` over the
// case list, so what is pinned here is ground truth rather than a transcription
// of it. That matters more than usual for this domain: every rule is a
// threshold, and a transcription that read `>= 15` as `> 15` would be invisible
// until someone with exactly fifteen transactions never saw a budget card.

private const val DOMAIN = "suggestions"

private fun count(o: JsonObject, key: String): Int =
    o[key]?.jsonPrimitive?.int ?: 0

private fun usage(o: JsonObject): UsageCounts = UsageCounts(
    accounts = count(o, "accounts"),
    transactions = count(o, "transactions"),
    subscriptions = count(o, "subscriptions"),
    loans = count(o, "loans"),
    budgets = count(o, "budgets"),
    goals = count(o, "goals"),
    splitGroups = count(o, "splitGroups"),
    receipts = count(o, "receipts"),
    recurring = count(o, "recurring"),
    holdings = count(o, "holdings"),
    creditCards = count(o, "creditCards"),
    creditCardAccounts = count(o, "creditCardAccounts"),
)

fun registerSuggestionsVectors() {
    FunctionRegistry.register(DOMAIN, "pickSuggestions") { input ->
        val o = input.jsonObject
        val picked = pickSuggestions(
            usage = usage(o.getValue("usage").jsonObject),
            dismissed = o.getValue("dismissed").jsonArray.map { it.jsonPrimitive.content }.toSet(),
            isPaid = o.getValue("isPaid").jsonPrimitive.boolean,
            max = o.getValue("max").jsonPrimitive.int,
        )
        // The ids, not the enum names: what crosses the wire (and what a
        // dismissal persists) is web's own string union.
        JsonArray(picked.map { JsonPrimitive(it.id) })
    }
}
