package com.sanvya.app.ui.components

import androidx.compose.foundation.layout.size
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.semantics.clearAndSetSemantics
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.sanvya.app.theme.LocalSanvyaColors
import com.sanvya.app.theme.SanvyaFont

/**
 * An icon from the bundled Material Symbols Rounded subset — the same font web
 * serves, so the glyph is identical rather than merely similar.
 *
 * Drawn as **text at a codepoint**, matching `MaterialIcon.tsx`. Two reasons
 * carried over from web: the subset is generated by codepoint (keeping the
 * ligature table would balloon 4 KB into 252 KB), and a codepoint that fails to
 * resolve paints nothing, whereas a ligature lookup would paint the literal
 * word "space_dashboard" into the navigation bar.
 *
 * Size is in `dp`, not `sp`: these sit inside fixed-size containers — 40dp
 * utility buttons, nav items — that do not grow with the text-size setting, so
 * a scaling glyph would overflow them. Web does the same; `.msym` takes an
 * explicit pixel size.
 *
 * @param contentDescription pass for a standalone icon button; leave null when
 *   the icon sits beside its own label, so a screen reader does not say it twice.
 */
@Composable
fun SanvyaIcon(
    glyph: String,
    modifier: Modifier = Modifier,
    size: Dp = 20.dp,
    tint: Color = LocalSanvyaColors.current.text,
    contentDescription: String? = null,
) {
    val density = androidx.compose.ui.platform.LocalDensity.current
    val fontSize = with(density) { size.toSp() }
    val semantics = if (contentDescription != null) {
        Modifier.semantics { this.contentDescription = contentDescription }
    } else {
        Modifier.clearAndSetSemantics { }
    }
    Text(
        text = glyph,
        modifier = modifier.size(size).then(semantics),
        style = TextStyle(
            fontFamily = SanvyaFont.icons,
            fontSize = fontSize,
            // A glyph box exactly as tall as the em means no extra leading, so
            // the icon centres in its size(size) box instead of sitting low.
            lineHeight = fontSize,
            textAlign = TextAlign.Center,
            color = tint,
        ),
    )
}
