package com.sanvya.app.ui.components

import androidx.compose.foundation.Canvas
import androidx.compose.foundation.layout.size
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.platform.LocalDensity
import androidx.compose.ui.semantics.clearAndSetSemantics
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import com.sanvya.app.theme.LocalSanvyaColors
import com.sanvya.app.theme.SanvyaFont

/**
 * An icon from the bundled Material Symbols Rounded subset — the same font web
 * serves, so the glyph is identical rather than merely similar.
 *
 * Drawn as **text at a codepoint**, matching `MaterialIcon.tsx`. Two reasons
 * carried over from web: the subset is generated by codepoint (keeping the
 * ligature table would balloon 4 KB into 252 KB), and a codepoint that fails to
 * resolve paints nothing, whereas a ligature lookup would paint the literal
 * word "space_dashboard" into the navigation bar.
 *
 * Size is in `dp`, not `sp`: these sit inside fixed-size containers — 40dp
 * utility buttons, nav items — that do not grow with the text-size setting, so
 * a scaling glyph would overflow them. Web does the same; `.msym` takes an
 * explicit pixel size.
 *
 * @param description pass for a standalone icon button; leave null when the
 *   icon sits beside its own label, so a screen reader does not say it twice.
 */
@Composable
fun SanvyaIcon(
    glyph: String,
    modifier: Modifier = Modifier,
    size: Dp = 20.dp,
    tint: Color = LocalSanvyaColors.current.text,
    description: String? = null,
) {
    val fontSize = with(LocalDensity.current) { size.toSp() }
    // Named `description`, not `contentDescription`: inside the semantics
    // lambda the receiver already has a `contentDescription` property, and a
    // parameter of the same name shadows it into an unresolvable assignment.
    val semanticsModifier = if (description != null) {
        Modifier.semantics { contentDescription = description }
    } else {
        Modifier.clearAndSetSemantics { }
    }
    Text(
        text = glyph,
        modifier = modifier.size(size).then(semanticsModifier),
        style = TextStyle(
            fontFamily = SanvyaFont.icons,
            fontSize = fontSize,
            // A line box exactly as tall as the em means no extra leading, so
            // the glyph centres in its size(size) box instead of sitting low.
            lineHeight = fontSize,
            textAlign = TextAlign.Center,
            color = tint,
        ),
    )
}

/**
 * Web's `ArrowUpIcon` — the send arrow, drawn rather than looked up.
 *
 * It is not a Material Symbol: `apps/web/src/ui/icons.tsx` draws it as a
 * stroked SVG, so there is no codepoint in the bundled subset to paint and
 * substituting a similar Material glyph would be a different shape at a
 * different weight. The two SVG commands (`M12 19 V5` and `M5 12l7-7 7 7`) are
 * transcribed here against a 24-unit box and scaled, which is the only way to
 * get web's icon rather than one like it.
 *
 * The first of that stroked set to be ported. The rest follow when a screen
 * needs them; a whole second icon family built ahead of its callers is a
 * component inventory nobody reads.
 */
@Composable
fun SanvyaArrowUpIcon(
    modifier: Modifier = Modifier,
    size: Dp = 19.dp,
    tint: Color = LocalSanvyaColors.current.text,
    strokeWidth: Dp = 2.dp,
    description: String? = null,
) {
    val semantics = if (description == null) {
        Modifier.clearAndSetSemantics { }
    } else {
        Modifier.semantics { contentDescription = description }
    }
    Canvas(modifier = modifier.size(size).then(semantics)) {
        val unit = this.size.minDimension / 24f
        val stroke = strokeWidth.toPx()
        fun p(x: Float, y: Float) = Offset(x * unit, y * unit)
        drawLine(tint, p(12f, 19f), p(12f, 5f), stroke, StrokeCap.Round)
        drawLine(tint, p(5f, 12f), p(12f, 5f), stroke, StrokeCap.Round)
        drawLine(tint, p(12f, 5f), p(19f, 12f), stroke, StrokeCap.Round)
    }
}
