package com.sanvya.app.ui.dashboard

// GENERATED by tools/parity/generate-tiles.mjs -- do not edit by hand.
// Sources: apps/web/src/dashboard.ts and apps/web/src/dashboard/tiles.tsx.
// Run `node tools/parity/generate-tiles.mjs` after changing either.

import android.content.res.Resources
import com.sanvya.app.i18n.S

/**
 * How wide a tile sits in the dashboard grid.
 *
 * Three steps, not a free drag. Web offers exactly these and stores the chosen
 * step rather than a pixel width, which is what lets the same saved dashboard
 * open on a phone and a tablet without arriving half off-screen.
 */
enum class TileWidth(val columns: Int) {
    SM(1),
    MD(2),
    LG(4),;

    /** Cycles on tap, exactly as web's width button does. */
    fun next(): TileWidth = entries[(ordinal + 1) % entries.size]
}

/** Every dashboard tile, in catalog order. */
enum class TileId(
    val key: String,
    val isPremium: Boolean,
    /** Nav route a tap on the tile opens, mirroring web's TILE_HREF. */
    val destination: String,
    private val label: (Resources) -> String,
) {
    RECENT("recent", false, "transactions", S.Dashboard::tileRecent),
    SPENDING("spending", false, "transactions", S.Dashboard::tileSpending),
    UPCOMING("upcoming", false, "recurring", S.Dashboard::tileUpcoming),
    TRENDS("trends", false, "insights", S.Dashboard::tileTrends),
    SPLITS("splits", false, "splits", S.Dashboard::tileSplits),
    BUDGETS("budgets", false, "budgets", S.Dashboard::tileBudgets),
    GOALS("goals", false, "goals", S.Dashboard::tileGoals),
    SUBSCRIPTIONS("subscriptions", false, "recurring", S.Dashboard::tileSubscriptions),
    CASHFLOW("cashflow", true, "insights", S.Dashboard::tileCashflow),
    NET_TREND("netTrend", true, "insights", S.Dashboard::tileNetTrend),
    BY_CATEGORY("byCategory", true, "insights", S.Dashboard::tileByCategory),
    BY_LABEL("byLabel", true, "insights", S.Dashboard::tileByLabel),
    MONTH_COMPARE("monthCompare", true, "insights", S.Dashboard::tileMonthCompare),
    CURRENCIES("currencies", false, "accounts", S.Dashboard::tileCurrencies),
    ;

    fun title(res: Resources): String = label(res)

    companion object {
        fun from(key: String?): TileId? = entries.firstOrNull { it.key == key }
    }
}

/** What a fresh install shows before the user touches anything. */
val DEFAULT_TILE_IDS: List<TileId> = listOf(TileId.RECENT, TileId.SPENDING, TileId.UPCOMING)

/** Storage keys, shared verbatim with web so a preference means one thing. */
const val TILE_ORDER_KEY = "dashboardTiles"
const val TILE_SIZE_KEY = "dashboardTileSizes"
