// GENERATED by tools/parity/generate-assistant-tools.mjs -- do not edit.
// Source: apps/web/src/assistant/tools.ts (ASSISTANT_TOOLS + CONFIRM_TOOLS).
//
// The tool surface the assistant model is handed. Descriptions are PROMPT TEXT,
// not documentation: paraphrasing one changes how the model behaves, which is
// why this file is generated from web's array rather than transcribed.
//
// Mirrors Android's AssistantTools.kt.

import Foundation

/// One tool the model may call. `inputSchema` is JSON, verbatim, ready to send.
public struct AssistantTool: Equatable, Sendable {
    public let name: String
    public let description: String
    public let inputSchema: String
    /// Whether a call has to be confirmed by the user before it runs.
    ///
    /// Every financial WRITE is true. `remember` is the only false one, and web
    /// says why in its own description: it "runs silently, no confirmation".
    public let needsConfirm: Bool
}

public let assistantTools: [AssistantTool] = [
    AssistantTool(
        name: "create_goal",
        description: "Create a savings goal (e.g. for a purchase like an iPhone). Use the user's base currency unless they specify another.",
        inputSchema: "{\"type\":\"object\",\"properties\":{\"name\":{\"type\":\"string\",\"description\":\"Short goal name, e.g. 'iPhone 16'.\"},\"target_amount\":{\"type\":\"number\",\"description\":\"Target amount in major units (e.g. 79900 for ₹79,900).\"},\"by_date\":{\"type\":\"string\",\"description\":\"Optional target date, ISO YYYY-MM-DD.\"},\"currency\":{\"type\":\"string\",\"description\":\"ISO currency code; defaults to the base currency.\"}},\"required\":[\"name\",\"target_amount\"]}",
        needsConfirm: true
    ),
    AssistantTool(
        name: "reserve_to_goal",
        description: "Set aside (block) money from a savings account toward an existing goal.",
        inputSchema: "{\"type\":\"object\",\"properties\":{\"goal_name\":{\"type\":\"string\",\"description\":\"Name of the goal to reserve money for.\"},\"amount\":{\"type\":\"number\",\"description\":\"Amount to reserve, in major units.\"}},\"required\":[\"goal_name\",\"amount\"]}",
        needsConfirm: true
    ),
    AssistantTool(
        name: "create_budget",
        description: "Create a spending budget with a monthly/weekly/etc. limit.",
        inputSchema: "{\"type\":\"object\",\"properties\":{\"name\":{\"type\":\"string\",\"description\":\"Budget name, e.g. 'Festival shopping'.\"},\"limit_amount\":{\"type\":\"number\",\"description\":\"Limit in major units.\"},\"period\":{\"type\":\"string\",\"enum\":[\"daily\",\"weekly\",\"monthly\",\"yearly\"],\"description\":\"Recurring period.\"},\"currency\":{\"type\":\"string\",\"description\":\"ISO currency code; defaults to base currency.\"}},\"required\":[\"name\",\"limit_amount\",\"period\"]}",
        needsConfirm: true
    ),
    AssistantTool(
        name: "record_transaction",
        description: "Record an income or expense the user tells you about (e.g. 'log ₹200 for coffee'). Books it on a real account (their named one, else the first account). Not for splitting bills with friends.",
        inputSchema: "{\"type\":\"object\",\"properties\":{\"type\":{\"type\":\"string\",\"enum\":[\"expense\",\"income\"],\"description\":\"Whether money went out (expense) or came in (income).\"},\"amount\":{\"type\":\"number\",\"description\":\"Amount in major units.\"},\"description\":{\"type\":\"string\",\"description\":\"Short description, e.g. 'Coffee'.\"},\"category\":{\"type\":\"string\",\"description\":\"Optional category name (matched to an existing category).\"},\"account\":{\"type\":\"string\",\"description\":\"Optional account name to use; defaults to the first account.\"}},\"required\":[\"type\",\"amount\"]}",
        needsConfirm: true
    ),
    AssistantTool(
        name: "create_subscription",
        description: "Add a recurring subscription (e.g. Netflix) so it's tracked in the user's monthly obligations.",
        inputSchema: "{\"type\":\"object\",\"properties\":{\"name\":{\"type\":\"string\",\"description\":\"Subscription name, e.g. 'Netflix'.\"},\"amount\":{\"type\":\"number\",\"description\":\"Amount per billing cycle, in major units.\"},\"billing_cycle\":{\"type\":\"string\",\"enum\":[\"daily\",\"weekly\",\"monthly\",\"yearly\"],\"description\":\"Billing cycle.\"}},\"required\":[\"name\",\"amount\",\"billing_cycle\"]}",
        needsConfirm: true
    ),
    AssistantTool(
        name: "create_group",
        description: "Create a split group or trip (for sharing expenses with friends). For a trip, include its dates. After creating, tell the user to invite people from Groups & trips → Invite.",
        inputSchema: "{\"type\":\"object\",\"properties\":{\"name\":{\"type\":\"string\",\"description\":\"Group/trip name, e.g. 'Goa'.\"},\"kind\":{\"type\":\"string\",\"enum\":[\"group\",\"trip\"],\"description\":\"'trip' for a dated getaway, 'group' for an ongoing household/flatmates group.\"},\"start_date\":{\"type\":\"string\",\"description\":\"Trip start date, ISO YYYY-MM-DD (optional; for trips).\"},\"end_date\":{\"type\":\"string\",\"description\":\"Trip end date, ISO YYYY-MM-DD (optional; for trips).\"},\"auto_split\":{\"type\":\"boolean\",\"description\":\"If true (and dates are set), expenses added within the dates auto-split equally with the group.\"}},\"required\":[\"name\",\"kind\"]}",
        needsConfirm: true
    ),
    AssistantTool(
        name: "remember",
        description: "Save ONE short, durable fact about the user for future chats (a lasting goal, preference, income cadence, or constraint). Use sparingly — not one-off details. Runs silently, no confirmation.",
        inputSchema: "{\"type\":\"object\",\"properties\":{\"fact\":{\"type\":\"string\",\"description\":\"One concise fact, under ~120 characters.\"}},\"required\":[\"fact\"]}",
        needsConfirm: false
    ),
]

/// True when a call must be confirmed. Unknown names are NOT confirmed, matching web's Set lookup.
public func assistantToolNeedsConfirm(_ name: String) -> Bool {
    assistantTools.contains { $0.name == name && $0.needsConfirm }
}
