import Foundation

// GENERATED FILE - do not hand-edit.
// Source: apps/web/src/categorize/seeds.ts (SEED_RULES)
//         apps/web/src/categorize/normalize.ts (STOP_WORDS, NOISE_TOKENS)
// Regenerate with: node tools/parity/generate-category-seeds.mjs

/// The auto-categoriser's cold-start tables, exactly as web writes them.
/// 
/// SEED_RULES maps a keyword to a category NAME, not an id -- the ids are the
/// user's own and are resolved at runtime by buildSeedMap(). NOISE_TOKENS and
/// STOP_WORDS decide which tokens survive normalisation at all, which is why
/// they are generated too: one platform missing a bank code silently changes
/// what every statement row categorises as.
public enum CategorySeeds {
    /// keyword -> category NAME, in web's own order. Kept as an ARRAY of pairs,
    /// not a Dictionary: Swift dictionaries have no defined iteration order at
    /// all, and buildSeedList's tie-break depends on this one.
    public static let seedRules: [(keyword: String, category: String)] = [
        ("uber", "Transport"),
        ("ola", "Transport"),
        ("lyft", "Transport"),
        ("metro", "Transport"),
        ("train", "Transport"),
        ("bus", "Transport"),
        ("flight", "Transport"),
        ("indigo", "Transport"),
        ("airasia", "Transport"),
        ("fuel", "Transport"),
        ("petrol", "Transport"),
        ("shell", "Transport"),
        ("swiggy", "Food & Dining"),
        ("zomato", "Food & Dining"),
        ("ubereats", "Food & Dining"),
        ("doordash", "Food & Dining"),
        ("starbucks", "Food & Dining"),
        ("mcdonalds", "Food & Dining"),
        ("kfc", "Food & Dining"),
        ("dominos", "Food & Dining"),
        ("restaurant", "Food & Dining"),
        ("cafe", "Food & Dining"),
        ("coffee", "Food & Dining"),
        ("tea", "Food & Dining"),
        ("lunch", "Food & Dining"),
        ("dinner", "Food & Dining"),
        ("breakfast", "Food & Dining"),
        ("pizza", "Food & Dining"),
        ("burger", "Food & Dining"),
        ("meal", "Food & Dining"),
        ("snacks", "Food & Dining"),
        ("chocolate", "Food & Dining"),
        ("icecream", "Food & Dining"),
        ("blinkit", "Groceries"),
        ("zepto", "Groceries"),
        ("instamart", "Groceries"),
        ("bigbasket", "Groceries"),
        ("dmart", "Groceries"),
        ("whole foods", "Groceries"),
        ("walmart", "Groceries"),
        ("target", "Groceries"),
        ("grocery", "Groceries"),
        ("groceries", "Groceries"),
        ("milk", "Groceries"),
        ("bread", "Groceries"),
        ("eggs", "Groceries"),
        ("vegetables", "Groceries"),
        ("veggies", "Groceries"),
        ("fruits", "Groceries"),
        ("rice", "Groceries"),
        ("oil", "Groceries"),
        ("sugar", "Groceries"),
        ("amazon", "Shopping"),
        ("flipkart", "Shopping"),
        ("myntra", "Shopping"),
        ("ajio", "Shopping"),
        ("zara", "Shopping"),
        ("h&m", "Shopping"),
        ("shoes", "Shopping"),
        ("shirt", "Shopping"),
        ("tshirt", "Shopping"),
        ("clothes", "Shopping"),
        ("dress", "Shopping"),
        ("jeans", "Shopping"),
        ("jacket", "Shopping"),
        ("bag", "Shopping"),
        ("watch", "Shopping"),
        ("medicine", "Health"),
        ("pharmacy", "Health"),
        ("chemist", "Health"),
        ("doctor", "Health"),
        ("hospital", "Health"),
        ("clinic", "Health"),
        ("gym", "Health"),
        ("salon", "Personal Care"),
        ("haircut", "Personal Care"),
        ("spa", "Personal Care"),
        ("netflix", "Subscriptions"),
        ("spotify", "Subscriptions"),
        ("youtube", "Subscriptions"),
        ("prime video", "Subscriptions"),
        ("disney", "Subscriptions"),
        ("apple", "Subscriptions"),
        ("google", "Subscriptions"),
        ("steam", "Entertainment"),
        ("movie", "Entertainment"),
        ("rent", "Housing"),
        ("electricity", "Utilities"),
        ("water", "Utilities"),
        ("wifi", "Utilities"),
        ("internet", "Utilities"),
        ("airtel", "Utilities"),
        ("jio", "Utilities"),
        ("swiggyinstamart", "Groceries"),
        ("eatfit", "Food & Dining"),
        ("faasos", "Food & Dining"),
        ("behrouz", "Food & Dining"),
        ("chaayos", "Food & Dining"),
        ("haldiram", "Food & Dining"),
        ("barbeque", "Food & Dining"),
        ("biryani", "Food & Dining"),
        ("rapido", "Transport"),
        ("irctc", "Transport"),
        ("redbus", "Transport"),
        ("makemytrip", "Transport"),
        ("goibibo", "Transport"),
        ("ixigo", "Transport"),
        ("fastag", "Transport"),
        ("hpcl", "Transport"),
        ("bpcl", "Transport"),
        ("ioc", "Transport"),
        ("indianoil", "Transport"),
        ("uberride", "Transport"),
        ("parking", "Transport"),
        ("toll", "Transport"),
        ("bbnow", "Groceries"),
        ("jiomart", "Groceries"),
        ("reliancefresh", "Groceries"),
        ("moreretail", "Groceries"),
        ("naturebasket", "Groceries"),
        ("licious", "Groceries"),
        ("meesho", "Shopping"),
        ("nykaa", "Shopping"),
        ("tatacliq", "Shopping"),
        ("snapdeal", "Shopping"),
        ("croma", "Shopping"),
        ("reliancedigital", "Shopping"),
        ("decathlon", "Shopping"),
        ("ikea", "Shopping"),
        ("lenskart", "Shopping"),
        ("firstcry", "Shopping"),
        ("pharmeasy", "Health"),
        ("netmeds", "Health"),
        ("apollo", "Health"),
        ("onemg", "Health"),
        ("tata1mg", "Health"),
        ("practo", "Health"),
        ("cultfit", "Health"),
        ("hotstar", "Subscriptions"),
        ("sonyliv", "Subscriptions"),
        ("zee5", "Subscriptions"),
        ("jiocinema", "Subscriptions"),
        ("audible", "Subscriptions"),
        ("youtubepremium", "Subscriptions"),
        ("googleone", "Subscriptions"),
        ("icloud", "Subscriptions"),
        ("openai", "Subscriptions"),
        ("chatgpt", "Subscriptions"),
        ("bookmyshow", "Entertainment"),
        ("pvr", "Entertainment"),
        ("inox", "Entertainment"),
        ("vodafone", "Utilities"),
        ("vi", "Utilities"),
        ("bsnl", "Utilities"),
        ("tataplay", "Utilities"),
        ("actfibernet", "Utilities"),
        ("adani", "Utilities"),
        ("tatapower", "Utilities"),
        ("bescom", "Utilities"),
        ("mseb", "Utilities"),
        ("gas", "Utilities"),
        ("recharge", "Utilities"),
        ("broadband", "Utilities"),
        ("zerodha", "Investments"),
        ("groww", "Investments"),
        ("upstox", "Investments"),
        ("coin", "Investments"),
        ("kuvera", "Investments"),
        ("indmoney", "Investments"),
        ("lic", "Insurance"),
        ("policybazaar", "Insurance"),
        ("insurance", "Insurance"),
        ("premium", "Insurance"),
        ("udemy", "Education"),
        ("coursera", "Education"),
        ("unacademy", "Education"),
        ("byjus", "Education"),
        ("tuition", "Education"),
        ("school", "Education"),
        ("college", "Education"),
        ("course", "Education"),
        ("salary", "Salary"),
        ("paycheck", "Salary"),
        ("bonus", "Bonus"),
        ("dividend", "Dividends"),
        ("refund", "Refunds"),
    ]

    public static let stopWords: Set<String> = [
        "the",
        "and",
        "or",
        "to",
        "for",
        "in",
        "on",
        "at",
        "with",
        "a",
        "an",
        "is",
        "of",
    ]

    public static let noiseTokens: Set<String> = [
        "upi",
        "imps",
        "neft",
        "rtgs",
        "ach",
        "ecs",
        "pos",
        "atm",
        "emi",
        "nach",
        "vps",
        "mmt",
        "ift",
        "inb",
        "chq",
        "cheque",
        "clg",
        "int",
        "intl",
        "txn",
        "trf",
        "transfer",
        "tfr",
        "payment",
        "paytm",
        "gpay",
        "phonepe",
        "bhim",
        "razorpay",
        "billdesk",
        "payu",
        "dr",
        "cr",
        "debit",
        "credit",
        "debited",
        "credited",
        "paid",
        "recd",
        "received",
        "rev",
        "reversal",
        "refund",
        "charge",
        "charges",
        "fee",
        "gst",
        "tax",
        "hdfc",
        "hdfcbank",
        "icic",
        "icici",
        "sbin",
        "sbi",
        "axis",
        "axisbank",
        "kkbk",
        "kotak",
        "yesb",
        "pnb",
        "boi",
        "cnrb",
        "canara",
        "utib",
        "idfb",
        "idfc",
        "fdrl",
        "federal",
        "indb",
        "indus",
        "indusind",
        "barb",
        "baroda",
        "ubin",
        "union",
        "bank",
        "ybl",
        "okhdfcbank",
        "okicici",
        "oksbi",
        "okaxis",
        "apl",
        "ibl",
        "axl",
        "paytmqr",
        "waaxis",
        "wahdfcbank",
        "yapl",
        "airtel",
        "freecharge",
        "jupiteraxis",
        "fam",
        "ref",
        "refno",
        "no",
        "id",
        "num",
        "number",
        "acct",
        "account",
        "ac",
        "info",
        "rrn",
        "www",
        "com",
        "in",
        "ltd",
        "limited",
        "pvt",
        "private",
        "india",
        "online",
        "order",
        "purchase",
        "spent",
        "transaction",
        "vpa",
        "collect",
        "req",
        "mandate",
        "autopay",
    ]
}
