#!/usr/bin/env node
/**
 * tools/parity/generate-icons.mjs
 *
 * Native icon maps, generated from the single list web renders from:
 * `MATERIAL_ICON` in apps/web/src/ui/MaterialIcon.tsx.
 *
 * Web draws icons as **codepoints** in a subset of Material Symbols Rounded
 * (see apps/web/public/fonts/README.md for why codepoints and not ligatures).
 * Both native apps bundle a TTF of that same subset, so all three platforms
 * paint the identical glyph — as opposed to Android reaching for
 * `Icons.Default.*` and iOS for SF Symbols, which are three different icon
 * families wearing similar names.
 *
 * Emits:
 *   apps/android/app/src/main/java/com/sanvya/app/theme/Icons.kt
 *   apps/ios/App/Theme/Icons.swift
 *
 * The font itself is rebuilt by tools/parity/build-fonts.sh, not by this
 * script — it needs fontTools. Run that whenever an icon is ADDED here.
 *
 * Usage: node tools/parity/generate-icons.mjs
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = process.env.SANVYA_REPO_ROOT
  ? path.resolve(process.env.SANVYA_REPO_ROOT)
  : path.resolve(__dirname, "../..");

const SRC = path.join(REPO_ROOT, "apps/web/src/ui/MaterialIcon.tsx");
const ANDROID_OUT = path.join(
  REPO_ROOT,
  "apps/android/app/src/main/java/com/sanvya/app/theme/Icons.kt",
);
const IOS_OUT = path.join(REPO_ROOT, "apps/ios/App/Theme/Icons.swift");

const src = readFileSync(SRC, "utf8");
const block = src.slice(
  src.indexOf("export const MATERIAL_ICON"),
  src.indexOf("} as const;"),
);

const icons = [];
const re = /^\s*([a-z0-9_]+):\s*"\\u([0-9a-fA-F]{4})",/gm;
let m;
while ((m = re.exec(block))) icons.push([m[1], m[2].toLowerCase()]);

if (icons.length === 0) {
  console.error("Parsed 0 icons from MaterialIcon.tsx — the source shape changed. Fix this script rather than committing an empty map.");
  process.exit(1);
}
// `--codepoints` prints ONLY the U+ list, so build-fonts.sh can capture it with
// a command substitution and the font can never be subset from a different
// reading of the source than the maps are generated from.
if (process.argv.includes("--codepoints")) {
  process.stdout.write(icons.map(([, cp]) => `U+${cp}`).join(","));
  process.exit(0);
}

console.log(`icons: ${icons.length} names parsed from MaterialIcon.tsx`);

const camel = (s) => s.replace(/_([a-z0-9])/g, (_, c) => c.toUpperCase());

const BANNER = [
  "// GENERATED FILE — do not hand-edit.",
  "// Source: apps/web/src/ui/MaterialIcon.tsx (MATERIAL_ICON)",
  "// Regenerate with: node tools/parity/generate-icons.mjs",
  "// Adding an icon also requires rebuilding the font: tools/parity/build-fonts.sh",
].join("\n");

const kt = `package com.sanvya.app.theme

${BANNER}

/**
 * Material Symbols Rounded codepoints, drawn from the bundled subset font
 * (\`res/font/sanvya_icons.ttf\`) — the same 4 KB subset web serves, so a glyph
 * is identical across web, Android and iOS.
 *
 * Rendered as text, not as an ImageVector: the subset is generated by
 * codepoint, and a codepoint that fails to resolve paints nothing, whereas a
 * ligature-based lookup would paint the literal word "space_dashboard" into
 * the navigation bar.
 */
object SanvyaIcons {
${icons.map(([name, cp]) => `    const val ${camel(name)} = "\\u${cp}"`).join("\n")}

    /** Web's own name for the icon, for spec cross-checks and tests. */
    val byWebName: Map<String, String> = mapOf(
${icons.map(([name, cp]) => `        "${name}" to "\\u${cp}",`).join("\n")}
    )
}
`;

const swift = `import SwiftUI

${BANNER}

/**
 Material Symbols Rounded codepoints, drawn from the bundled subset font
 (\`SanvyaIcons.ttf\`) — the same subset web serves, so a glyph is identical
 across web, Android and iOS.

 Rendered as text rather than an SF Symbol: SF Symbols is a different icon
 family, and matching it name-for-name would still give a different shape.
 */
public enum SanvyaIcons {
${icons.map(([name, cp]) => `    public static let ${camel(name)} = "\\u{${cp}}"`).join("\n")}

    /// Web's own name for the icon, for spec cross-checks and tests.
    public static let byWebName: [String: String] = [
${icons.map(([name, cp]) => `        "${name}": "\\u{${cp}}",`).join("\n")}
    ]
}
`;

mkdirSync(path.dirname(ANDROID_OUT), { recursive: true });
mkdirSync(path.dirname(IOS_OUT), { recursive: true });
writeFileSync(ANDROID_OUT, kt);
writeFileSync(IOS_OUT, swift);

console.log("Wrote:");
console.log(" -", path.relative(REPO_ROOT, ANDROID_OUT));
console.log(" -", path.relative(REPO_ROOT, IOS_OUT));
