import SwiftUI

/**
 An icon from the bundled Material Symbols Rounded subset — the same font web
 serves, so the glyph is identical rather than merely similar.

 Drawn as **text at a codepoint**, matching `MaterialIcon.tsx`. Two reasons
 carried over: the subset is generated by codepoint (keeping the ligature table
 would balloon 4 KB into 252 KB), and a codepoint that fails to resolve paints
 nothing, whereas a ligature lookup would paint the literal word
 "space_dashboard" into the navigation bar.

 Size is fixed, not Dynamic-Type-scaled: these sit inside fixed containers —
 40pt utility buttons, nav items — that do not grow with the text-size setting,
 so a scaling glyph would overflow them. Web behaves the same way; `.msym` takes
 an explicit pixel size.

 - Parameter accessibilityLabel: pass for a standalone icon button; leave nil
   when the icon sits beside its own label, so VoiceOver does not say it twice.
 */
public struct SanvyaIconView: View {
    private let glyph: String
    private let size: CGFloat
    private let tint: Color
    private let accessibilityLabel: String?

    public init(
        _ glyph: String,
        size: CGFloat = 20,
        tint: Color = .text,
        accessibilityLabel: String? = nil
    ) {
        self.glyph = glyph
        self.size = size
        self.tint = tint
        self.accessibilityLabel = accessibilityLabel
    }

    public var body: some View {
        Text(verbatim: glyph)
            .font(SanvyaFont.icon(size: size))
            .foregroundStyle(tint)
            .frame(width: size, height: size)
            .modifier(IconAccessibility(label: accessibilityLabel))
    }
}

private struct IconAccessibility: ViewModifier {
    let label: String?
    func body(content: Content) -> some View {
        if let label {
            content.accessibilityLabel(label).accessibilityAddTraits(.isImage)
        } else {
            content.accessibilityHidden(true)
        }
    }
}

/**
 Web's `ArrowUpIcon` — the send arrow, drawn rather than looked up.

 It is not a Material Symbol: `apps/web/src/ui/icons.tsx` draws it as a stroked
 SVG, so there is no codepoint in the bundled subset to paint and substituting a
 similar Material glyph would be a different shape at a different weight. The
 two SVG commands (`M12 19 V5` and `M5 12l7-7 7 7`) are transcribed here against
 a 24-unit box and scaled, which is the only way to get web's icon rather than
 one like it.

 The first of that stroked set to be ported. The rest follow when a screen needs
 them; a whole second icon family built ahead of its callers is a component
 inventory nobody reads. Mirrors Android's `SanvyaArrowUpIcon`.
 */
public struct SanvyaArrowUpIconView: View {
    private let size: CGFloat
    private let tint: Color
    private let strokeWidth: CGFloat

    public init(size: CGFloat = 19, tint: Color = .text, strokeWidth: CGFloat = 2) {
        self.size = size
        self.tint = tint
        self.strokeWidth = strokeWidth
    }

    public var body: some View {
        Canvas { context, canvasSize in
            let unit = min(canvasSize.width, canvasSize.height) / 24
            func point(_ x: CGFloat, _ y: CGFloat) -> CGPoint { CGPoint(x: x * unit, y: y * unit) }
            var path = Path()
            path.move(to: point(12, 19))
            path.addLine(to: point(12, 5))
            path.move(to: point(5, 12))
            path.addLine(to: point(12, 5))
            path.addLine(to: point(19, 12))
            context.stroke(
                path,
                with: .color(tint),
                style: StrokeStyle(lineWidth: strokeWidth, lineCap: .round, lineJoin: .round)
            )
        }
        .frame(width: size, height: size)
        .accessibilityHidden(true)
    }
}
