import SwiftUI

/**
 An icon from the bundled Material Symbols Rounded subset — the same font web
 serves, so the glyph is identical rather than merely similar.

 Drawn as **text at a codepoint**, matching `MaterialIcon.tsx`. Two reasons
 carried over: the subset is generated by codepoint (keeping the ligature table
 would balloon 4 KB into 252 KB), and a codepoint that fails to resolve paints
 nothing, whereas a ligature lookup would paint the literal word
 "space_dashboard" into the navigation bar.

 Size is fixed, not Dynamic-Type-scaled: these sit inside fixed containers —
 40pt utility buttons, nav items — that do not grow with the text-size setting,
 so a scaling glyph would overflow them. Web behaves the same way; `.msym` takes
 an explicit pixel size.

 - Parameter accessibilityLabel: pass for a standalone icon button; leave nil
   when the icon sits beside its own label, so VoiceOver does not say it twice.
 */
public struct SanvyaIconView: View {
    private let glyph: String
    private let size: CGFloat
    private let tint: Color
    private let accessibilityLabel: String?

    public init(
        _ glyph: String,
        size: CGFloat = 20,
        tint: Color = .text,
        accessibilityLabel: String? = nil
    ) {
        self.glyph = glyph
        self.size = size
        self.tint = tint
        self.accessibilityLabel = accessibilityLabel
    }

    public var body: some View {
        Text(verbatim: glyph)
            .font(SanvyaFont.icon(size: size))
            .foregroundStyle(tint)
            .frame(width: size, height: size)
            .modifier(IconAccessibility(label: accessibilityLabel))
    }
}

private struct IconAccessibility: ViewModifier {
    let label: String?
    func body(content: Content) -> some View {
        if let label {
            content.accessibilityLabel(label).accessibilityAddTraits(.isImage)
        } else {
            content.accessibilityHidden(true)
        }
    }
}
