import SwiftUI

/**
 An icon from the bundled Material Symbols Rounded subset — the same font web
 serves, so the glyph is identical rather than merely similar.

 Drawn as **text at a codepoint**, matching `MaterialIcon.tsx`. Two reasons
 carried over: the subset is generated by codepoint (keeping the ligature table
 would balloon 4 KB into 252 KB), and a codepoint that fails to resolve paints
 nothing, whereas a ligature lookup would paint the literal word
 "space_dashboard" into the navigation bar.

 Size is fixed, not Dynamic-Type-scaled: these sit inside fixed containers —
 40pt utility buttons, nav items — that do not grow with the text-size setting,
 so a scaling glyph would overflow them. Web behaves the same way; `.msym` takes
 an explicit pixel size.

 - Parameter accessibilityLabel: pass for a standalone icon button; leave nil
   when the icon sits beside its own label, so VoiceOver does not say it twice.
 */
public struct SanvyaIconView: View {
    private let glyph: String
    private let size: CGFloat
    private let tint: Color
    private let accessibilityLabel: String?

    public init(
        _ glyph: String,
        size: CGFloat = 20,
        tint: Color = .text,
        accessibilityLabel: String? = nil
    ) {
        self.glyph = glyph
        self.size = size
        self.tint = tint
        self.accessibilityLabel = accessibilityLabel
    }

    public var body: some View {
        Text(verbatim: glyph)
            .font(SanvyaFont.icon(size: size))
            .foregroundStyle(tint)
            .frame(width: size, height: size)
            .modifier(IconAccessibility(label: accessibilityLabel))
    }
}

private struct IconAccessibility: ViewModifier {
    let label: String?
    func body(content: Content) -> some View {
        if let label {
            content.accessibilityLabel(label).accessibilityAddTraits(.isImage)
        } else {
            content.accessibilityHidden(true)
        }
    }
}

/**
 Web's `ArrowUpIcon` — the send arrow, drawn rather than looked up.

 It is not a Material Symbol: `apps/web/src/ui/icons.tsx` draws it as a stroked
 SVG, so there is no codepoint in the bundled subset to paint and substituting a
 similar Material glyph would be a different shape at a different weight. The
 two SVG commands (`M12 19 V5` and `M5 12l7-7 7 7`) are transcribed here against
 a 24-unit box and scaled, which is the only way to get web's icon rather than
 one like it.

 The first of that stroked set to be ported. The rest follow when a screen needs
 them; a whole second icon family built ahead of its callers is a component
 inventory nobody reads. Mirrors Android's `SanvyaArrowUpIcon`.
 */
public struct SanvyaArrowUpIconView: View {
    private let size: CGFloat
    private let tint: Color
    private let strokeWidth: CGFloat

    public init(size: CGFloat = 19, tint: Color = .text, strokeWidth: CGFloat = 2) {
        self.size = size
        self.tint = tint
        self.strokeWidth = strokeWidth
    }

    public var body: some View {
        Canvas { context, canvasSize in
            let unit = min(canvasSize.width, canvasSize.height) / 24
            func point(_ x: CGFloat, _ y: CGFloat) -> CGPoint { CGPoint(x: x * unit, y: y * unit) }
            var path = Path()
            path.move(to: point(12, 19))
            path.addLine(to: point(12, 5))
            path.move(to: point(5, 12))
            path.addLine(to: point(12, 5))
            path.addLine(to: point(19, 12))
            context.stroke(
                path,
                with: .color(tint),
                style: StrokeStyle(lineWidth: strokeWidth, lineCap: .round, lineJoin: .round)
            )
        }
        .frame(width: size, height: size)
        .accessibilityHidden(true)
    }
}

/**
 Web's `MicIcon` — the composer's mic, drawn like the arrow above it.

 Same reason: `icons.tsx` draws it as a stroked SVG, so there is no codepoint in
 the bundled Material subset to paint. Its three commands — a pill from (9,2) to
 (15,14), the cradle arc `M5 10v1 a7 7 0 0 0 14 0 v-1`, and the stand
 `M12 18 V22` — are transcribed against the same 24-unit box.

 The arc is the one part worth reading twice. Angles are measured from three
 o'clock and the canvas is y-DOWN, so 90° is the BOTTOM of the circle, not the
 top; and `clockwise: false` means "increasing angle", which on a y-down canvas
 looks clockwise. So the cradle — which bulges downward — is 0° to 180° with
 `clockwise: false`, drawn right-to-left, and the two stems are ordered to
 match. Either flag flipped turns it into a hat over the capsule. Android's port
 has the mirror-image note.
 */
public struct SanvyaMicIconView: View {
    private let size: CGFloat
    private let tint: Color
    private let strokeWidth: CGFloat

    public init(size: CGFloat = 19, tint: Color = .text, strokeWidth: CGFloat = 1.8) {
        self.size = size
        self.tint = tint
        self.strokeWidth = strokeWidth
    }

    public var body: some View {
        Canvas { context, canvasSize in
            let unit = min(canvasSize.width, canvasSize.height) / 24
            func u(_ v: CGFloat) -> CGFloat { v * unit }

            var path = Path()
            // The capsule: x 9..15, y 2..14, radius 3 — with a width of 6 and a
            // radius of 3 the corners meet, so it is a pill, not a rounded box.
            path.addRoundedRect(
                in: CGRect(x: u(9), y: u(2), width: u(6), height: u(12)),
                cornerSize: CGSize(width: u(3), height: u(3))
            )
            path.move(to: CGPoint(x: u(19), y: u(10)))
            path.addLine(to: CGPoint(x: u(19), y: u(11)))
            path.addArc(
                center: CGPoint(x: u(12), y: u(11)),
                radius: u(7),
                startAngle: .degrees(0),
                endAngle: .degrees(180),
                clockwise: false
            )
            path.addLine(to: CGPoint(x: u(5), y: u(10)))
            path.move(to: CGPoint(x: u(12), y: u(18)))
            path.addLine(to: CGPoint(x: u(12), y: u(22)))

            context.stroke(
                path,
                with: .color(tint),
                style: StrokeStyle(lineWidth: strokeWidth, lineCap: .round, lineJoin: .round)
            )
        }
        .frame(width: size, height: size)
        .accessibilityHidden(true)
    }
}
